import type { Surface, SurfaceCard } from "@/components/PantavionPublicShell";

export const homePillars: SurfaceCard[] = [
  { title: "AI Execution", href: "/intelligence/routing", body: "Intent, planning, routing, capability matching and governed execution." },
  { title: "Messages & Connect", href: "/messages", body: "Native communication, groups, secure channels, contacts and future live translation." },
  { title: "Market & Ads", href: "/market", body: "Listings, services, sponsored placements and business discovery without intrusive ads." },
  { title: "Creator Studio", href: "/studio", body: "Video, cartoon, voice, music, dubbing, radio messages and multilingual media creation." },
  { title: "Build Services", href: "/build-services", body: "Websites, apps, automations, AI assistants, dashboards and professional digital systems." },
  { title: "Kernel Control", href: "/kernel/run", body: "The sovereign internal brain for routing, monitoring, resilience and future self-repair." },
];

export const revenuePillars: SurfaceCard[] = [
  { title: "Founding Access", body: "Early commercial access with fair-use limits, supporting infrastructure and platform growth." },
  { title: "Market Listings", body: "Paid local and global listings: sell, rent, request, offer, promote and close listings cleanly." },
  { title: "Business Promotion", body: "Business pages, sponsored listings, featured offers and professional discovery surfaces." },
  { title: "Build Services", body: "Paid websites, apps, automations, AI assistants, dashboards and custom systems." },
  { title: "Media and Radio", body: "Sponsored shows, creator channels, promoted videos, music, events, radio messages and audio spots." },
  { title: "Creator Studio", body: "Voice, video, cartoon, dubbing, content packs and future AI execution credits." },
];

export const surfaces: Record<string, Surface> = {
  pricing: {
    kicker: "Pantavion Pricing",
    title: "Start with Founding Access. Expand into market, studio, media and business plans.",
    lead: "Pantavion pricing begins simple so the world can discover the platform. Plans later expand into listings, creator tools, build services, media, radio, business, AI execution and elite access.",
    primaryHref: "/founding-access",
    primaryLabel: "Founding Access",
    secondaryHref: "/contact",
    secondaryLabel: "Contact",
    cards: [
      { title: "Free Preview", body: "Public routes and launch foundation for discovery.", status: "Free" },
      { title: "Founding Access", body: "30-day founding trial with fair-use limits. Intended to support development and platform rollout.", status: "Stripe Pending" },
      { title: "Business and Creator Plans", body: "Listings, media, studio, business pages and build services release progressively.", status: "Next" },
    ],
    notes: [
      "Pantavion provides tools, access and digital capabilities. It does not guarantee personal, social, romantic, professional or financial outcomes.",
      "No intrusive ads inside private communication, safety routes or protected youth experiences.",
    ],
  },
  foundingAccess: {
    kicker: "Pantavion Founding Access",
    title: "Support the foundation of a global AI, communication, media, work and language ecosystem.",
    lead: "Founding Access supports the development of Pantavion One: a living platform for AI execution, social connection, communication, creation, work, services, marketplace, media, safety and global language access.",
    primaryHref: "/pricing",
    primaryLabel: "View Pricing",
    secondaryHref: "/contact",
    secondaryLabel: "Contact Pantavion",
    cards: [
      { title: "30-Day Trial", body: "A launch trial with fair-use limits so users can discover Pantavion without exposing the platform to abuse.", status: "Trial" },
      { title: "Development Support", body: "Subscriptions support infrastructure, AI systems, media surfaces, security, language tools and legal rollout.", status: "Commercial" },
      { title: "No False Guarantees", body: "Pantavion provides tools and access. It does not guarantee user income or regulated outcomes.", status: "Trust" },
    ],
  },
  messages: {
    kicker: "Pantavion Messages",
    title: "The native communication layer of Pantavion.",
    lead: "Pantavion Messages is designed for one-to-one chat, groups, channels, communities, secure communication, voice and video routes, live translation and lawful contact import.",
    primaryHref: "/connect",
    primaryLabel: "Open Connect",
    secondaryHref: "/import-world",
    secondaryLabel: "Import World",
    cards: [
      { title: "Pantavion Connect", body: "Our own communication channel, not dependency on WhatsApp, Viber, Messenger, LINE or Telegram.", status: "Native" },
      { title: "Secure Channels", body: "Private higher-security rooms for verified users, leaders, professionals, creators and protected communities.", status: "Secure" },
      { title: "Translation by Design", body: "Built for multilingual communication, captions, voice routes and global language access.", status: "Language" },
    ],
  },
  connect: {
    kicker: "Pantavion Connect",
    title: "Bring people into one governed communication ecosystem.",
    lead: "Pantavion Connect is the future native chat, call, group, community and channel system of Pantavion, designed to operate alongside lawful bridges and import tools from the wider digital world.",
    primaryHref: "/messages",
    primaryLabel: "Messages",
    secondaryHref: "/safety",
    secondaryLabel: "Safety",
    cards: [
      { title: "Native Chat", body: "Messaging, groups, channels and communities under Pantavion identity and safety rules.", status: "Foundation" },
      { title: "Lawful Bridges", body: "External contacts and exports only through official APIs, OAuth, uploads or user consent.", status: "Consent" },
      { title: "Privacy Controls", body: "Users decide what is public, private, imported, deleted, hidden or connected.", status: "Control" },
    ],
  },
  importWorld: {
    kicker: "Import My World",
    title: "Bring contacts, messages, emails, social handles and digital history into one living screen.",
    lead: "Pantavion Import My World is designed for lawful user-controlled import: phone contacts, email contacts, CSV, vCard, exported chats, social handles, work accounts and media archives.",
    primaryHref: "/messages",
    primaryLabel: "Messages",
    secondaryHref: "/privacy",
    secondaryLabel: "Privacy",
    cards: [
      { title: "Consent First", body: "No hidden scraping. No secret imports. Every source requires authorization or user-provided export.", status: "Consent" },
      { title: "Global App Atlas", body: "Apps tracked by country, region, category, legal import path and integration priority.", status: "Atlas" },
      { title: "Universal Inbox Direction", body: "Long-term goal: one governed center for messages, email, social and work communication.", status: "Roadmap" },
    ],
  },
  market: {
    kicker: "Pantavion Market",
    title: "Professional listings, services, business discovery and local-to-global opportunities.",
    lead: "Pantavion Market organizes sales, rentals, requests, services, businesses, events and opportunities by country, region, city, community, parish, neighborhood and category.",
    primaryHref: "/ads",
    primaryLabel: "Ads Center",
    secondaryHref: "/pricing",
    secondaryLabel: "Pricing",
    cards: [
      { title: "Local Listings", body: "Sell, rent, request or offer by country, region, city, community and category.", status: "Market" },
      { title: "Business Listings", body: "Professional business pages, verified sellers and service visibility.", status: "Business" },
      { title: "Close Easily", body: "Listings can become Active, Sold, Rented, Paused, Closed or Expired with simple controls.", status: "Lifecycle" },
    ],
    notes: [
      "Market revenue comes from listings, boosts, featured placements, business pages and sponsored listings.",
      "Illegal goods, scams, unsafe claims and hidden sponsorships are not allowed.",
    ],
  },
  ads: {
    kicker: "Pantavion Ads Center",
    title: "Promotion belongs in dedicated commercial surfaces, not inside private life.",
    lead: "Pantavion Ads Center is designed for sponsored listings, business promotion, local visibility, media promotion and marketplace discovery.",
    primaryHref: "/market",
    primaryLabel: "Open Market",
    secondaryHref: "/legal",
    secondaryLabel: "Legal Center",
    cards: [
      { title: "No Intrusive Ads", body: "No ads inside private messages, protected youth areas, safety routes or personal communication.", status: "Rule" },
      { title: "Sponsored Disclosure", body: "Paid placements must be clearly labeled as sponsored or promoted.", status: "Trust" },
      { title: "Country Rules", body: "Promotion rules adapt by country, age zone, category, risk and legal boundary.", status: "Compliance" },
    ],
  },
  buildServices: {
    kicker: "Pantavion Build Services",
    title: "Websites, apps, automations, AI assistants and digital systems built through Pantavion.",
    lead: "Pantavion Build Services helps people and businesses turn ideas into websites, apps, automations, dashboards, AI assistants and business systems through structured AI-assisted professional delivery.",
    primaryHref: "/contact",
    primaryLabel: "Request Build",
    secondaryHref: "/pricing",
    secondaryLabel: "Pricing",
    cards: [
      { title: "Build Brief", body: "Idea analysis, project scope, timeline, budget and technical roadmap.", status: "Service" },
      { title: "Websites and Apps", body: "Landing pages, business sites, MVPs, dashboards, marketplaces and custom systems.", status: "Build" },
      { title: "Support Plans", body: "Monthly maintenance, improvements, automation updates and professional service packages.", status: "Support" },
    ],
  },
  services: {
    kicker: "Pantavion Services",
    title: "A professional services layer for people, businesses, creators and specialists.",
    lead: "Pantavion Services will organize service offers, requests, professional profiles, business pages, local providers and global digital services under safety, verification and country rules.",
    primaryHref: "/market",
    primaryLabel: "Open Market",
    secondaryHref: "/build-services",
    secondaryLabel: "Build Services",
    cards: [
      { title: "Service Listings", body: "Offer professional services by country, city, community, category and language.", status: "Listings" },
      { title: "Verified Providers", body: "Future verification for higher-trust businesses and professionals.", status: "Trust" },
      { title: "Digital Services", body: "Remote services, AI services, design, development, translation and business support.", status: "Global" },
    ],
  },
  work: {
    kicker: "Pantavion Work",
    title: "Office, assistant, secretary, productivity and business execution inside one system.",
    lead: "Pantavion Work is the professional work surface for documents, email drafts, meetings, research, reports, office tasks, executive assistant workflows and business operations.",
    primaryHref: "/build-services",
    primaryLabel: "Build Services",
    secondaryHref: "/pricing",
    secondaryLabel: "Pricing",
    cards: [
      { title: "Office Assistant", body: "Emails, documents, summaries, research, reports and task organization.", status: "Work" },
      { title: "Secretary Workflows", body: "Meeting preparation, reminders, client replies, proposals and scheduling direction.", status: "Assistant" },
      { title: "Fair-Use Trial", body: "Trial access must have limits to prevent abuse and provider cost overload.", status: "Protection" },
    ],
  },
  radio: {
    kicker: "Pantavion Radio",
    title: "Multilingual internet radio, journalism, sports, music and community voice.",
    lead: "Pantavion Radio is a future media network for talk shows, sports commentary, journalism, culture, creator shows, licensed music, community messages, sponsor slots and AI-assisted multilingual voice participation.",
    primaryHref: "/media",
    primaryLabel: "Media",
    secondaryHref: "/studio",
    secondaryLabel: "Creator Studio",
    cards: [
      { title: "Listener Messages", body: "Text or voice messages can be moderated, translated and converted to approved human-style voice for broadcast.", status: "Voice" },
      { title: "Sports and Journalism", body: "Analysis, commentary, community reports and sponsored segments with rights and source controls.", status: "Media" },
      { title: "Music Rights", body: "Commercial music requires licenses. Initial focus should be talk, original, licensed or royalty-cleared content.", status: "Rights" },
    ],
  },
  studio: {
    kicker: "Pantavion Creator Studio",
    title: "Create video, cartoon, voice, music, dubbing and multilingual media.",
    lead: "Pantavion Creator Studio helps people, creators and businesses create, edit, animate, translate, publish and promote videos, cartoon content, voice media, songs, messages and multilingual digital stories.",
    primaryHref: "/media",
    primaryLabel: "Media",
    secondaryHref: "/radio",
    secondaryLabel: "Radio",
    cards: [
      { title: "Video Studio", body: "Upload, edit, caption, translate, cut clips, improve audio and prepare creator or business videos.", status: "Video" },
      { title: "Cartoon Studio", body: "Create original cartoon-style videos and animations without copying protected characters or brands.", status: "Cartoon" },
      { title: "Voice Studio", body: "Polish user-owned voices, licensed synthetic voices, dubbing, radio messages and business audio spots.", status: "Voice" },
    ],
  },
  media: {
    kicker: "Pantavion Media",
    title: "Video, photos, music, creators, events, channels and professional media promotion.",
    lead: "Pantavion Media gives creators, artists, businesses and communities a professional place to publish, promote and monetize videos, photos, music, radio, events and channels with rights protection.",
    primaryHref: "/studio",
    primaryLabel: "Creator Studio",
    secondaryHref: "/ads",
    secondaryLabel: "Ads Center",
    cards: [
      { title: "Creator Channels", body: "Future channels for creators, artists, journalists, educators, businesses and communities.", status: "Creator" },
      { title: "Promoted Media", body: "Paid visibility for videos, songs, events, galleries and business media pages.", status: "Revenue" },
      { title: "Rights Protection", body: "User-owned, licensed or royalty-cleared material only. No copied copyrighted content.", status: "Rights" },
    ],
  },
  elite: {
    kicker: "Pantavion Elite",
    title: "High-trust private communication and verified professional circles.",
    lead: "Pantavion Elite is the future high-security layer for leaders, public figures, executives, creators, protected communities and premium professional circles.",
    primaryHref: "/contact",
    primaryLabel: "Request Access",
    secondaryHref: "/security",
    secondaryLabel: "Security",
    cards: [
      { title: "Approval-Based Access", body: "Elite access should require verification, identity controls and consent-based visibility.", status: "Restricted" },
      { title: "Secure Channels", body: "Private rooms, controlled viewing, restricted sharing and high-trust communication.", status: "Security" },
      { title: "Founder Reports", body: "Kernel and control-room reporting for high-value operations and approvals.", status: "Control" },
    ],
  },
  adultConnect: {
    kicker: "Pantavion Adult Connect",
    title: "Future restricted 18+ private social and relationship zone.",
    lead: "Adult Connect is a future restricted revenue pillar only for verified adults 18+, with strict age verification, country compliance, consent, privacy, safety and separate payment review.",
    primaryHref: "/safety",
    primaryLabel: "Safety",
    secondaryHref: "/legal",
    secondaryLabel: "Legal",
    cards: [
      { title: "No Minors", body: "No adult content, discovery, ads or recommendations may reach minors or protected youth experiences.", status: "Strict" },
      { title: "Separate Payment Review", body: "Adult explicit services must not be placed under Stripe without adult-compatible processor and legal review.", status: "Payment" },
      { title: "Consent and Country Law", body: "Explicit media and adult interaction require consent, moderation, privacy controls and country-specific legality.", status: "Compliance" },
    ],
    notes: [
      "This route is a policy foundation, not an active adult marketplace.",
      "Adult systems must be isolated from general social, youth, Stripe founding access and public feeds.",
    ],
  },
  safety: {
    kicker: "Pantavion Safety",
    title: "Safety, law, identity, reports, minors protection and user trust.",
    lead: "Pantavion Safety organizes protected experiences, reports, age rules, consent, moderation, commercial integrity, adult boundaries, financial safety and health content guardrails.",
    primaryHref: "/minors",
    primaryLabel: "Minors",
    secondaryHref: "/legal",
    secondaryLabel: "Legal Center",
    cards: [
      { title: "Minors Protection", body: "No adult zones, targeting, unsafe content or inappropriate ads for minors.", status: "Protected" },
      { title: "Reports", body: "Illegal content, abuse, impersonation, exploitation and unsafe behavior require escalation workflows.", status: "Reports" },
      { title: "Risk Boundaries", body: "Finance, health, adult, media rights and marketplace categories require stricter rules.", status: "Guardrails" },
    ],
  },
  minors: {
    kicker: "Pantavion Minors Protection",
    title: "Age-aware safety for children, teens and protected users.",
    lead: "Pantavion must protect minors with age-aware design, no adult access, no targeted adult ads, restricted discovery, safe communication and country-specific rules.",
    primaryHref: "/safety",
    primaryLabel: "Safety",
    secondaryHref: "/privacy",
    secondaryLabel: "Privacy",
    cards: [
      { title: "No Adult Leakage", body: "Adult content, profiles, ads and recommendations must never appear in protected youth surfaces.", status: "Rule" },
      { title: "Age Gates", body: "Age-aware onboarding and restrictions are required before sensitive features go live.", status: "Access" },
      { title: "Family and Education", body: "Future youth areas should focus on learning, safety, family, culture and language.", status: "Positive" },
    ],
  },
  legal: {
    kicker: "Pantavion Legal Center",
    title: "Legal, privacy, terms, refunds, safety, country compliance and commercial integrity.",
    lead: "The Legal Center organizes the trust foundation for Pantavion before Stripe, marketplace, media, messages, adult restricted areas and country-specific systems expand.",
    primaryHref: "/terms",
    primaryLabel: "Terms",
    secondaryHref: "/privacy",
    secondaryLabel: "Privacy",
    cards: [
      { title: "Terms", body: "Rules for access, acceptable use, launch-stage features, commercial surfaces and user conduct.", href: "/terms", status: "Live" },
      { title: "Privacy", body: "Consent-first import, user control, sensitive areas and data protection direction.", href: "/privacy", status: "Live" },
      { title: "Refund Policy", body: "Founding access, listings, promotions and build services need clear cancellation and refund logic.", href: "/refund-policy", status: "Live" },
    ],
  },
  terms: {
    kicker: "Pantavion Terms",
    title: "Terms of Service foundation.",
    lead: "Pantavion terms foundation for launch. Final production terms require formal legal review before regulated or high-risk services go live.",
    primaryHref: "/legal",
    primaryLabel: "Legal Center",
    secondaryHref: "/contact",
    secondaryLabel: "Contact",
    cards: [
      { title: "Service Stage", body: "Some routes are live foundations while advanced providers, payments, databases, voice systems and regulated services release progressively.", status: "Launch" },
      { title: "Acceptable Use", body: "No illegal activity, abuse, harassment, exploitation, scams, non-consensual intimate content, spam or rights infringement.", status: "Rules" },
      { title: "No Guarantees", body: "Pantavion does not guarantee income, financial returns, medical results, personal outcomes or social success.", status: "Trust" },
    ],
  },
  privacy: {
    kicker: "Pantavion Privacy",
    title: "Privacy Policy foundation.",
    lead: "Pantavion privacy foundation for user control, consent-first import, age-aware experiences and future data portability.",
    primaryHref: "/legal",
    primaryLabel: "Legal Center",
    secondaryHref: "/import-world",
    secondaryLabel: "Import World",
    cards: [
      { title: "Consent First", body: "No contacts, messages, emails, social handles, files or communication history should be imported without authorization.", status: "Consent" },
      { title: "User Control", body: "Users should be able to manage, disconnect, delete, export and review their data as the platform matures.", status: "Control" },
      { title: "Sensitive Areas", body: "Minors, adult zones, finance, health and private communication require stricter privacy controls.", status: "Sensitive" },
    ],
  },
  refundPolicy: {
    kicker: "Pantavion Refund Policy",
    title: "Refund and cancellation foundation.",
    lead: "Pantavion refund foundation for founding subscriptions, listings, promotions, creator tools, media, radio and professional services.",
    primaryHref: "/pricing",
    primaryLabel: "Pricing",
    secondaryHref: "/contact",
    secondaryLabel: "Contact",
    cards: [
      { title: "Founding Access", body: "Users should have clear cancellation before renewal. Trial terms must be visible before checkout.", status: "Subscription" },
      { title: "Listings and Promotion", body: "Paid visibility periods should state duration, category, location and refund limits before purchase.", status: "Market" },
      { title: "Build Services", body: "Custom work may require deposits, milestones and separate written scope.", status: "Services" },
    ],
  },
  contact: {
    kicker: "Pantavion Contact",
    title: "Contact Pantavion.",
    lead: "Contact and support foundation for users, businesses, founders, creators, partners, safety requests, Stripe/payment questions and build services.",
    primaryHref: "/pricing",
    primaryLabel: "Pricing",
    secondaryHref: "/",
    secondaryLabel: "Home",
    cards: [
      { title: "General Contact", body: "Questions, partnerships, business listings, build services and founding access.", status: "Support" },
      { title: "Safety Requests", body: "Minors, abuse, illegal content, impersonation or urgent safety concerns require priority review.", status: "Safety" },
      { title: "Business and Payments", body: "Stripe, invoices, cancellation questions and business listings need clear support workflows.", status: "Commercial" },
    ],
  },
  cookies: {
    kicker: "Pantavion Cookies",
    title: "Cookie and tracking policy foundation.",
    lead: "Pantavion needs a clear cookie policy before analytics, ads, marketplace measurement, Stripe tracking and personalization expand.",
    primaryHref: "/privacy",
    primaryLabel: "Privacy",
    secondaryHref: "/legal",
    secondaryLabel: "Legal",
    cards: [
      { title: "Essential Cookies", body: "Required for security, login, checkout, language and platform operation.", status: "Essential" },
      { title: "Analytics", body: "Analytics should be introduced transparently and respect regional consent requirements.", status: "Consent" },
      { title: "Ads and Market", body: "Commercial surfaces must not use sensitive targeting or hidden tracking.", status: "Trust" },
    ],
  },
  acceptableUse: {
    kicker: "Pantavion Acceptable Use",
    title: "Acceptable use policy foundation.",
    lead: "Pantavion requires clear rules for communication, AI execution, marketplace, media, adult restricted systems, import tools and build services.",
    primaryHref: "/legal",
    primaryLabel: "Legal",
    secondaryHref: "/safety",
    secondaryLabel: "Safety",
    cards: [
      { title: "No Abuse", body: "No harassment, hate, exploitation, spam, scams, illegal goods or unsafe conduct.", status: "Rule" },
      { title: "No Rights Abuse", body: "No copyright infringement, unauthorized voice cloning, deepfake misuse or non-consensual media.", status: "Rights" },
      { title: "No Sensitive Harm", body: "Finance, health, adult and minors-related content must follow stricter rules.", status: "Risk" },
    ],
  },
  download: {
    kicker: "Pantavion Download",
    title: "Install Pantavion as a web app when the production domain is ready.",
    lead: "Pantavion should become installable across phone, tablet and desktop as a PWA, with fast loading, clean routes and lightweight public pages.",
    primaryHref: "/",
    primaryLabel: "Home",
    secondaryHref: "/pricing",
    secondaryLabel: "Pricing",
    cards: [
      { title: "Mobile First", body: "The visible app must stay lightweight while the Kernel handles deep complexity internally.", status: "Speed" },
      { title: "PWA Direction", body: "Manifest, icons and install path are prepared for production hardening.", status: "PWA" },
      { title: "Custom Domain Needed", body: "pantavion.com should be connected after the public foundation routes stabilize.", status: "Domain" },
    ],
  },
};

export const allPublicPaths = [
  "/",
  "/pricing",
  "/founding-access",
  "/messages",
  "/connect",
  "/import-world",
  "/market",
  "/ads",
  "/build-services",
  "/services",
  "/work",
  "/radio",
  "/studio",
  "/media",
  "/elite",
  "/adult-connect",
  "/safety",
  "/minors",
  "/legal",
  "/terms",
  "/privacy",
  "/refund-policy",
  "/contact",
  "/cookies",
  "/acceptable-use",
  "/download",
  "/kernel/run",
  "/signals",
  "/security",
  "/language",
  "/dashboard",
  "/intelligence/routing",
];
