import {
  loadPantavionWorkPackageQueue,
  savePantavionWorkPackageQueue,
  type PantavionWorkPackage,
  type PantavionWorkPackageQueue,
} from "./autonomous-work-package-coordinator";
import {
  createAutonomousGithubPullRequest,
  preflightAutonomousGithubPullRequest,
  type GithubPatchFile,
} from "../autonomous-code/github-autonomous-writer";
import { appendPantavionRuntimeLedgerEvent } from "./runtime-ledger";

export type PantavionWorkPackagePrMode = "dry_run" | "github_pr";

export type PantavionWorkPackagePrExecutorInput = {
  readonly packageId?: string;
  readonly mode: PantavionWorkPackagePrMode;
  readonly sourceRunId?: string;
};

export type PantavionWorkPackagePrExecutorResult =
  | {
      readonly ok: true;
      readonly marker: "pantavion_work_package_pr_executor_c9g_v1";
      readonly mode: PantavionWorkPackagePrMode;
      readonly executed: boolean;
      readonly workPackage: PantavionWorkPackage;
      readonly filesPrepared: readonly string[];
      readonly branch?: string;
      readonly pullRequestUrl?: string;
      readonly queue: ReturnType<typeof summarizeWorkPackagePrExecutorQueue>;
    }
  | {
      readonly ok: false;
      readonly marker: "pantavion_work_package_pr_executor_c9g_v1";
      readonly mode: PantavionWorkPackagePrMode;
      readonly executed: boolean;
      readonly reason: string;
      readonly workPackage?: PantavionWorkPackage;
      readonly queue: ReturnType<typeof summarizeWorkPackagePrExecutorQueue>;
    };

function nowIso(): string {
  return new Date().toISOString();
}

function sanitizeName(value: string): string {
  return value
    .replace(/[^a-zA-Z0-9]+/g, " ")
    .trim()
    .split(/\s+/)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("") || "PantavionGeneratedWorkPackage";
}

function moduleNameFromPath(filePath: string): string {
  const base = filePath.split("/").pop() ?? filePath;
  return sanitizeName(base.replace(/\.[^.]+$/, ""));
}

function selectWorkPackage(
  queue: PantavionWorkPackageQueue,
  packageId?: string,
): PantavionWorkPackage | undefined {
  if (packageId) {
    return queue.packages.find((pkg) => pkg.id === packageId);
  }

  return [...queue.packages]
    .reverse()
    .find((pkg) => pkg.state === "claimed");
}

function updateWorkPackage(
  queue: PantavionWorkPackageQueue,
  packageId: string,
  updater: (pkg: PantavionWorkPackage) => PantavionWorkPackage,
): PantavionWorkPackageQueue {
  return {
    version: 1,
    updatedAt: nowIso(),
    packages: queue.packages.map((pkg) => (pkg.id === packageId ? updater(pkg) : pkg)),
  };
}

function renderGeneratedContract(pkg: PantavionWorkPackage, filePath: string): string {
  const exportName = `${moduleNameFromPath(filePath)}PantavionContract`;

  return [
    "// Auto-generated by Pantavion Work Package PR Executor C9-G.",
    "// This is an internal kernel contract, not a public UI feature.",
    "// It must pass audits, build, typecheck, protected-domain policy and founder/maintainer review before merge.",
    "",
    `export const ${exportName} = {`,
    `  packageId: ${JSON.stringify(pkg.id)},`,
    `  title: ${JSON.stringify(pkg.title)},`,
    `  capabilityFamily: ${JSON.stringify(pkg.capabilityFamily)},`,
    `  status: "work_package_contract_ready",`,
    `  risk: ${JSON.stringify(pkg.risk)},`,
    `  priority: ${JSON.stringify(pkg.priority)},`,
    `  generatedBy: "pantavion_work_package_pr_executor_c9g_v1",`,
    `  protectedDomains: ${JSON.stringify(pkg.protectedDomains)},`,
    `  requiredGates: ${JSON.stringify(pkg.requiredGates)},`,
    `  successSignals: ${JSON.stringify(pkg.successSignals)},`,
    "} as const;",
    "",
    `export type ${exportName} = typeof ${exportName};`,
    "",
    `export function plan${exportName}Execution(input: {`,
    "  readonly intent: string;",
    "  readonly context?: unknown;",
    "}) {",
    "  return {",
    "    ok: true,",
    `    packageId: ${exportName}.packageId,`,
    `    capabilityFamily: ${exportName}.capabilityFamily,`,
    "    intent: input.intent,",
    "    context: input.context,",
    `    requiredGates: ${exportName}.requiredGates,`,
    "    nextAction: \"connect_provider_or_runtime_executor\",",
    "    mergePolicy: \"pull_request_only_with_required_gates\",",
    "  };",
    "}",
    "",
  ].join("\n");
}

function filesForWorkPackage(pkg: PantavionWorkPackage): GithubPatchFile[] {
  return pkg.targetFiles.map((filePath) => ({
    path: filePath,
    content: renderGeneratedContract(pkg, filePath),
    message: `feat(kernel): scaffold ${pkg.id}`,
  }));
}

function prTitle(pkg: PantavionWorkPackage): string {
  return `feat(kernel): execute work package ${pkg.id}`;
}

function prBody(pkg: PantavionWorkPackage): string {
  return [
    "## Pantavion Autonomous Work Package PR",
    "",
    `Package: ${pkg.id}`,
    `Title: ${pkg.title}`,
    `Capability family: ${pkg.capabilityFamily}`,
    `Risk: ${pkg.risk}`,
    `Priority: ${pkg.priority}`,
    `Protected domains: ${pkg.protectedDomains.length > 0 ? pkg.protectedDomains.join(", ") : "none"}`,
    "",
    "## Summary",
    "",
    pkg.summary,
    "",
    "## Required gates",
    "",
    ...pkg.requiredGates.map((gate) => `- ${gate}`),
    "",
    "## Safety",
    "",
    "- This PR is generated from the Pantavion work package queue.",
    "- No direct production mutation is allowed.",
    "- Protected-domain work requires founder-aware review before merge.",
    "- No raw Water/DWG/DXF/KMZ/KML/private infrastructure data may be exposed.",
    "- No secrets may be committed.",
  ].join("\n");
}

export function summarizeWorkPackagePrExecutorQueue() {
  const queue = loadPantavionWorkPackageQueue();

  return {
    ok: true,
    marker: "pantavion_work_package_pr_executor_summary_c9g_v1",
    updatedAt: queue.updatedAt,
    totalPackages: queue.packages.length,
    claimedPackages: queue.packages.filter((pkg) => pkg.state === "claimed").length,
    completedPackages: queue.packages.filter((pkg) => pkg.state === "completed").length,
    failedPackages: queue.packages.filter((pkg) => pkg.state === "failed").length,
    blockedPackages: queue.packages.filter((pkg) => pkg.state === "blocked").length,
    nextClaimed: queue.packages.filter((pkg) => pkg.state === "claimed").slice(-5),
  };
}

export async function executeClaimedPantavionWorkPackageAsPr(
  input: PantavionWorkPackagePrExecutorInput,
): Promise<PantavionWorkPackagePrExecutorResult> {
  const queue = loadPantavionWorkPackageQueue();
  const pkg = selectWorkPackage(queue, input.packageId);
  const executed = input.mode === "github_pr";

  if (!pkg) {
    appendPantavionRuntimeLedgerEvent({
      runId: input.sourceRunId,
      eventType: "error_recorded",
      severity: "warning",
      kernelFamily: "Pantavion Work Package PR Executor",
      message: "No claimed work package available for PR execution.",
      protectedDomains: [],
      metadata: {
        marker: "pantavion_work_package_pr_executor_c9g_v1",
      },
    });

    return {
      ok: false,
      marker: "pantavion_work_package_pr_executor_c9g_v1",
      mode: input.mode,
      executed,
      reason: "No claimed work package available.",
      queue: summarizeWorkPackagePrExecutorQueue(),
    };
  }

  if (pkg.state !== "claimed") {
    return {
      ok: false,
      marker: "pantavion_work_package_pr_executor_c9g_v1",
      mode: input.mode,
      executed,
      reason: `Work package is not claimed. Current state: ${pkg.state}.`,
      workPackage: pkg,
      queue: summarizeWorkPackagePrExecutorQueue(),
    };
  }

  const files = filesForWorkPackage(pkg);
  const preflight = preflightAutonomousGithubPullRequest({ files });

  if (!preflight.ok) {
    appendPantavionRuntimeLedgerEvent({
      runId: input.sourceRunId,
      eventType: "error_recorded",
      severity: "error",
      kernelFamily: "Pantavion Work Package PR Executor",
      message: "Work package PR preflight failed.",
      protectedDomains: pkg.protectedDomains,
      metadata: {
        marker: "pantavion_work_package_pr_executor_c9g_v1",
        packageId: pkg.id,
        blockedReasons: preflight.blockedReasons,
      },
    });

    const failedQueue = updateWorkPackage(queue, pkg.id, (candidate) => ({
      ...candidate,
      state: "failed",
      failedAt: nowIso(),
      updatedAt: nowIso(),
      failureReason: `PR preflight failed: ${preflight.blockedReasons.join(" | ")}`,
    }));
    savePantavionWorkPackageQueue(failedQueue);

    return {
      ok: false,
      marker: "pantavion_work_package_pr_executor_c9g_v1",
      mode: input.mode,
      executed,
      reason: `PR preflight failed: ${preflight.blockedReasons.join(" | ")}`,
      workPackage: pkg,
      queue: summarizeWorkPackagePrExecutorQueue(),
    };
  }

  if (input.mode === "dry_run") {
    appendPantavionRuntimeLedgerEvent({
      runId: input.sourceRunId,
      eventType: "audit_passed",
      severity: "info",
      kernelFamily: "Pantavion Work Package PR Executor",
      message: "Work package PR dry run passed.",
      protectedDomains: pkg.protectedDomains,
      metadata: {
        marker: "pantavion_work_package_pr_executor_c9g_v1",
        packageId: pkg.id,
        filesPrepared: files.map((file) => file.path),
      },
    });

    return {
      ok: true,
      marker: "pantavion_work_package_pr_executor_c9g_v1",
      mode: input.mode,
      executed: false,
      workPackage: pkg,
      filesPrepared: files.map((file) => file.path),
      queue: summarizeWorkPackagePrExecutorQueue(),
    };
  }

  const pr = await createAutonomousGithubPullRequest({
    runId: `work-package-${pkg.id}`,
    title: prTitle(pkg),
    body: prBody(pkg),
    files,
  });

  if (!pr.ok) {
    appendPantavionRuntimeLedgerEvent({
      runId: input.sourceRunId,
      eventType: "error_recorded",
      severity: "error",
      kernelFamily: "Pantavion Work Package PR Executor",
      message: "Work package PR creation failed.",
      protectedDomains: pkg.protectedDomains,
      metadata: {
        marker: "pantavion_work_package_pr_executor_c9g_v1",
        packageId: pkg.id,
        reason: pr.reason,
      },
    });

    const failedQueue = updateWorkPackage(queue, pkg.id, (candidate) => ({
      ...candidate,
      state: "failed",
      failedAt: nowIso(),
      updatedAt: nowIso(),
      failureReason: pr.reason,
    }));
    savePantavionWorkPackageQueue(failedQueue);

    return {
      ok: false,
      marker: "pantavion_work_package_pr_executor_c9g_v1",
      mode: input.mode,
      executed,
      reason: pr.reason,
      workPackage: pkg,
      queue: summarizeWorkPackagePrExecutorQueue(),
    };
  }

  const completedPackage: PantavionWorkPackage = {
    ...pkg,
    state: "completed",
    completedAt: nowIso(),
    updatedAt: nowIso(),
  };

  const completedQueue = updateWorkPackage(queue, pkg.id, () => completedPackage);
  savePantavionWorkPackageQueue(completedQueue);

  appendPantavionRuntimeLedgerEvent({
    runId: input.sourceRunId,
    eventType: "pr_created",
    severity: pkg.protectedDomains.length > 0 ? "warning" : "info",
    kernelFamily: "Pantavion Work Package PR Executor",
    message: "Work package converted into GitHub PR.",
    protectedDomains: pkg.protectedDomains,
    metadata: {
      marker: "pantavion_work_package_pr_executor_c9g_v1",
      packageId: pkg.id,
      branch: pr.branch,
      pullRequestUrl: pr.pullRequestUrl,
      filesChanged: pr.filesChanged,
      requiresFounderApproval: pkg.protectedDomains.length > 0,
    },
  });

  if (pkg.protectedDomains.length > 0) {
    appendPantavionRuntimeLedgerEvent({
      runId: input.sourceRunId,
      eventType: "founder_gate_required",
      severity: "warning",
      kernelFamily: "Pantavion Work Package PR Executor",
      message: "Generated work-package PR touches protected domains and requires founder approval before merge.",
      protectedDomains: pkg.protectedDomains,
      metadata: {
        marker: "pantavion_work_package_pr_executor_c9g_v1",
        packageId: pkg.id,
        pullRequestUrl: pr.pullRequestUrl,
      },
    });
  }

  return {
    ok: true,
    marker: "pantavion_work_package_pr_executor_c9g_v1",
    mode: input.mode,
    executed,
    workPackage: completedPackage,
    filesPrepared: files.map((file) => file.path),
    branch: pr.branch,
    pullRequestUrl: pr.pullRequestUrl,
    queue: summarizeWorkPackagePrExecutorQueue(),
  };
}

export const pantavion_work_package_pr_executor_marker_v1 =
  "pantavion_work_package_pr_executor_c9g_v1";
