import type { ProductionStatus, RiskClass } from "./product-family-taxonomy";

export type RouteStatusRecord = {
  readonly path: string;
  readonly label: string;
  readonly status: ProductionStatus;
  readonly riskClass: RiskClass;
  readonly family: string;
  readonly visibleToPublic: boolean;
  readonly buttonRule: "active-link" | "disabled-with-label" | "hidden-until-ready";
  readonly owner: "kernel" | "product" | "legal" | "commercial" | "safety";
  readonly notes: string;
};

export const routeStatusRegistry = [
  {
    path: "/",
    label: "Home",
    status: "LIVE",
    riskClass: "LOW",
    family: "planet",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "product",
    notes: "Public premium baseline.",
  },
  {
    path: "/architecture",
    label: "Architecture",
    status: "LIVE",
    riskClass: "MEDIUM",
    family: "architecture",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "kernel",
    notes: "Master architecture route is live.",
  },
  {
    path: "/ai-feature-register",
    label: "AI Feature Register",
    status: "LIVE",
    riskClass: "HIGH",
    family: "ai-feature-register",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "kernel",
    notes: "AI zones and governance are public as foundation doctrine.",
  },
  {
    path: "/sos-interpreter",
    label: "SOS + Interpreter",
    status: "FOUNDATION",
    riskClass: "CRITICAL",
    family: "sos-interpreter",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "safety",
    notes: "Doctrine route live, operational emergency backend not yet claimed.",
  },
  {
    path: "/access-model",
    label: "Access Model",
    status: "LIVE",
    riskClass: "MEDIUM",
    family: "access-model",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "commercial",
    notes: "Access doctrine live before Stripe.",
  },
  {
    path: "/intelligence/competitive",
    label: "Competitive Intelligence",
    status: "LIVE",
    riskClass: "MEDIUM",
    family: "competitive-intelligence",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "kernel",
    notes: "Strategic intelligence route live.",
  },
  {
    path: "/kernel/audit",
    label: "Kernel Audit",
    status: "LIVE",
    riskClass: "HIGH",
    family: "kernel-audit",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "kernel",
    notes: "Audit route live.",
  },
  {
    path: "/readiness",
    label: "Production Readiness",
    status: "LIVE",
    riskClass: "HIGH",
    family: "kernel-audit",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "kernel",
    notes: "Classification and release gate dashboard.",
  },
  {
    path: "/pricing",
    label: "Pricing",
    status: "FOUNDATION",
    riskClass: "HIGH",
    family: "access-model",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "commercial",
    notes: "Must remain non-charging until Stripe/legal gates pass.",
  },
  {
    path: "/messages",
    label: "Messages",
    status: "FOUNDATION",
    riskClass: "HIGH",
    family: "messages",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "product",
    notes: "Native route can exist, but no external app scraping claims.",
  },
  {
    path: "/market",
    label: "Market",
    status: "FOUNDATION",
    riskClass: "HIGH",
    family: "marketplace",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "commercial",
    notes: "Listings foundation only until fraud and restricted categories are implemented.",
  },
  {
    path: "/studio",
    label: "Studio",
    status: "FOUNDATION",
    riskClass: "MEDIUM",
    family: "studio",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "product",
    notes: "Creator foundation, not full generation studio yet.",
  },
  {
    path: "/build-services",
    label: "Build Services",
    status: "FOUNDATION",
    riskClass: "MEDIUM",
    family: "build-services",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "commercial",
    notes: "Service route foundation.",
  },
  {
    path: "/radio",
    label: "Radio",
    status: "FOUNDATION",
    riskClass: "HIGH",
    family: "audio-radio",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "product",
    notes: "Audio/radio foundation, rights policy required before live media operations.",
  },
  {
    path: "/import-world",
    label: "Import World",
    status: "LEGAL_REVIEW",
    riskClass: "CRITICAL",
    family: "messages",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "legal",
    notes: "Only consent/API/export/import/official connector paths allowed.",
  },
  {
    path: "/legal",
    label: "Legal",
    status: "FOUNDATION",
    riskClass: "CRITICAL",
    family: "legal",
    visibleToPublic: true,
    buttonRule: "active-link",
    owner: "legal",
    notes: "Legal center foundation.",
  },
] as const satisfies readonly RouteStatusRecord[];

export const routeStatusSummary = {
  total: routeStatusRegistry.length,
  live: routeStatusRegistry.filter((route) => route.status === "LIVE").length,
  foundation: routeStatusRegistry.filter((route) => route.status === "FOUNDATION").length,
  legalReview: routeStatusRegistry.filter((route) => route.status === "LEGAL_REVIEW").length,
  critical: routeStatusRegistry.filter((route) => route.riskClass === "CRITICAL").length,
} as const;
