import { createHash } from "node:crypto";

export const SOVEREIGN_DRY_RUN_SCHEMA="pantavion.sovereign-execution-dry-run.v1" as const;
export const SOVEREIGN_DRY_RUN_POLICY="deterministic-non-authorizing-scheduler-v1" as const;
const ROOT=new Set(["manifestReceipt","manifestDecision","intentId","planId","evaluationTime","maxParallelTasks","tasks"]);
const TASK=new Set(["taskId","agentId","capability","cost","dependsOn","mode","sequence","requiredEvidence"]);
const ID=/^[a-zA-Z0-9][a-zA-Z0-9._:-]{0,159}$/; const CAP=/^[a-z][a-z0-9._:-]{0,127}$/; const SHA=/^[a-f0-9]{64}$/;
const EVIDENCE=new Set(["input_digest","output_digest","policy_receipt","budget_receipt","agent_lease_receipt","edge_sequence_receipt"]);
type Mode="sandbox"|"disconnected_edge";
export type DryRunTask={taskId:string;agentId:string;capability:string;cost:number;dependsOn:string[];mode:Mode;sequence:number;requiredEvidence:string[]};
export type DryRunRequest={manifestReceipt:string;manifestDecision:"DENY"|"MANIFEST_READY_FOR_OWNER_EXECUTION_REVIEW";intentId:string;planId:string;evaluationTime:string;maxParallelTasks:number;tasks:DryRunTask[]};
function rec(v:unknown,n:string){if(typeof v!=="object"||v===null||Array.isArray(v))throw new Error("invalid_dry_run:"+n);return v as Record<string,unknown>}
function exact(v:Record<string,unknown>,keys:Set<string>,n:string){for(const k of Object.keys(v))if(!keys.has(k))throw new Error(`invalid_dry_run:${n}_unknown_field:${k}`)}
function txt(v:unknown,n:string,p=ID){if(typeof v!=="string"||!p.test(v.trim()))throw new Error("invalid_dry_run:"+n);return v.trim().toLowerCase()}
function num(v:unknown,n:string,positive=false){if(typeof v!=="number"||!Number.isSafeInteger(v)||v<0||(positive&&v===0))throw new Error("invalid_dry_run:"+n);return v}
function list(v:unknown,n:string,p:RegExp,max:number){if(!Array.isArray(v)||v.length>max)throw new Error("invalid_dry_run:"+n);const a=v.map((x,i)=>txt(x,`${n}_${i}`,p));if(new Set(a).size!==a.length)throw new Error("invalid_dry_run:"+n+"_duplicate");return a.sort()}
export function parseSovereignDryRun(v:unknown):DryRunRequest{const r=rec(v,"object_required");exact(r,ROOT,"root");if(r.manifestDecision!=="DENY"&&r.manifestDecision!=="MANIFEST_READY_FOR_OWNER_EXECUTION_REVIEW")throw new Error("invalid_dry_run:manifestDecision");if(typeof r.evaluationTime!=="string"||!Number.isFinite(Date.parse(r.evaluationTime)))throw new Error("invalid_dry_run:evaluationTime");if(!Array.isArray(r.tasks)||r.tasks.length===0||r.tasks.length>32)throw new Error("invalid_dry_run:tasks");const tasks=r.tasks.map((raw,i)=>{const t=rec(raw,`task_${i}`);exact(t,TASK,`task_${i}`);if(t.mode!=="sandbox"&&t.mode!=="disconnected_edge")throw new Error(`invalid_dry_run:task_${i}_mode`);const evidence=list(t.requiredEvidence,`task_${i}_requiredEvidence`,CAP,6);if(evidence.some(x=>!EVIDENCE.has(x)))throw new Error(`invalid_dry_run:task_${i}_requiredEvidence_enum`);return{taskId:txt(t.taskId,`task_${i}_taskId`),agentId:txt(t.agentId,`task_${i}_agentId`),capability:txt(t.capability,`task_${i}_capability`,CAP),cost:num(t.cost,`task_${i}_cost`),dependsOn:list(t.dependsOn,`task_${i}_dependsOn`,ID,31),mode:t.mode,sequence:num(t.sequence,`task_${i}_sequence`),requiredEvidence:evidence}as DryRunTask});if(new Set(tasks.map(t=>t.taskId)).size!==tasks.length)throw new Error("invalid_dry_run:duplicate_task_id");return{manifestReceipt:txt(r.manifestReceipt,"manifestReceipt",SHA),manifestDecision:r.manifestDecision,intentId:txt(r.intentId,"intentId"),planId:txt(r.planId,"planId"),evaluationTime:new Date(r.evaluationTime).toISOString(),maxParallelTasks:num(r.maxParallelTasks,"maxParallelTasks",true),tasks}}
function stable(v:unknown):string{if(Array.isArray(v))return"["+v.map(stable).join(",")+"]";if(typeof v==="object"&&v!==null){const o=v as Record<string,unknown>;return"{"+Object.keys(o).sort().map(k=>JSON.stringify(k)+":"+stable(o[k])).join(",")+"}"}return JSON.stringify(v)??"null"}
export function compileSovereignDryRun(v:unknown){const q=parseSovereignDryRun(v);const reasons:string[]=[];if(q.manifestDecision!=="MANIFEST_READY_FOR_OWNER_EXECUTION_REVIEW")reasons.push("manifest_not_ready");if(q.maxParallelTasks>16)reasons.push("parallelism_limit_exceeded");const byId=new Map(q.tasks.map(t=>[t.taskId,t]));if(q.tasks.some(t=>t.dependsOn.includes(t.taskId)))reasons.push("self_dependency");if(q.tasks.some(t=>t.dependsOn.some(d=>!byId.has(d))))reasons.push("missing_dependency");const edge=q.tasks.filter(t=>t.mode==="disconnected_edge");if(edge.some(t=>t.sequence===0)||new Set(edge.map(t=>t.sequence)).size!==edge.length)reasons.push("invalid_edge_sequence");if(q.tasks.some(t=>!t.requiredEvidence.includes("input_digest")||!t.requiredEvidence.includes("output_digest")||!t.requiredEvidence.includes("policy_receipt")))reasons.push("mandatory_evidence_missing");if(edge.some(t=>!t.requiredEvidence.includes("edge_sequence_receipt")))reasons.push("edge_evidence_missing");
const pending=new Map(q.tasks.map(t=>[t.taskId,new Set(t.dependsOn)]));const waves:string[][]=[];const done=new Set<string>();while(done.size<q.tasks.length){const ready=[...pending].filter(([id,deps])=>!done.has(id)&&[...deps].every(d=>done.has(d))).map(([id])=>id).sort();if(!ready.length){reasons.push("dependency_cycle");break}for(let i=0;i<ready.length;i+=q.maxParallelTasks){const wave=ready.slice(i,i+q.maxParallelTasks);waves.push(wave);wave.forEach(id=>done.add(id))}}
const tasks=[...q.tasks].sort((a,b)=>a.taskId.localeCompare(b.taskId));const obligations=tasks.map(t=>({taskId:t.taskId,evidence:[...t.requiredEvidence].sort()}));const decision=reasons.length?"DENY":"DRY_RUN_READY_FOR_OWNER_REVIEW";const payload={schema:SOVEREIGN_DRY_RUN_SCHEMA,policyVersion:SOVEREIGN_DRY_RUN_POLICY,request:{...q,tasks},decision,reasons:[...new Set(reasons)],waves:decision==="DENY"?[]:waves,waveCount:decision==="DENY"?0:waves.length,taskCount:tasks.length,agentCount:new Set(tasks.map(t=>t.agentId)).size,totalCost:tasks.reduce((s,t)=>s+t.cost,0),evidenceObligationCount:obligations.reduce((s,o)=>s+o.evidence.length,0),obligations,simulationOnly:true,executionAllowed:false,executionStarted:false,resourcesReserved:false,budgetConsumedNow:false,agentsCreated:false,agentsActivated:false,edgeHandoffIssued:false,productionWriteAllowed:false,authorizationEffect:"none"};return{...payload,dryRunReceipt:createHash("sha256").update(stable(payload)).digest("hex")}}
