import type { PantavionTechnologySignalInput } from "./pantavion-evolution-engine";

export const pantavionCurrentTechnologySignals: PantavionTechnologySignalInput[] = [
  {
    id: "signal-agentic-cyber-2026-08-27",
    title: "Agentic AI is becoming a first-class cyber and operational risk",
    summary:
      "Recent primary, peer-reviewed and wire reporting indicates that increasingly autonomous AI agents require stronger containment, identity, permission, monitoring and incident-response controls.",
    domain: "agentic_ai",
    eventType: "security_incident",
    observedAt: "2026-08-27T00:00:00Z",
    jurisdictions: ["GLOBAL", "EU", "UK", "US"],
    productionRelevance: 94,
    humanBenefitPotential: 92,
    noveltyPotential: 90,
    riskIfIgnored: 97,
    reversibility: 82,
    evidence: [
      {
        title: "As AI agents go rogue, cyber insurers are adapting their policies",
        publisher: "Reuters",
        url: "https://www.reuters.com/legal/litigation/ai-agents-go-rogue-cyber-insurers-are-adapting-their-policies-2026-08-27/",
        publishedAt: "2026-08-27",
        tier: "reputable_wire",
      },
      {
        title: "Responding to the next frontier of critical cyber capabilities",
        publisher: "OpenAI",
        url: "https://openai.com/index/responding-next-frontier-critical-cyber-capabilities/",
        publishedAt: "2026-08-07",
        tier: "primary_vendor",
      },
      {
        title: "Agentic AI and cybersecurity, the story so far",
        publisher: "Nature Machine Intelligence",
        url: "https://www.nature.com/articles/s42256-026-01301-0",
        publishedAt: "2026-08-18",
        tier: "peer_reviewed",
      },
    ],
    foresightHypotheses: [
      { hypothesis: "Non-human AI identities become first-class security principals rather than being treated as ordinary service accounts.", confidence: 92 },
      { hypothesis: "Every agent receives capability-scoped, time-bounded permissions with explicit human and policy ownership.", confidence: 90 },
      { hypothesis: "Tool calls and inter-agent messages require signed provenance and policy-verifiable origin metadata.", confidence: 86 },
      { hypothesis: "Continuous runtime risk scoring becomes more important than one-time pre-deployment approval for autonomous agents.", confidence: 84 },
      { hypothesis: "Inter-agent communication channels move from open discovery toward allowlisted, purpose-bound communication fabrics.", confidence: 82 },
      { hypothesis: "Adversarial simulation and containment drills become standard release gates for high-autonomy agent workflows.", confidence: 80 },
      { hypothesis: "Platforms add automatic quarantine, privilege reduction and rollback when agent behaviour crosses defined boundaries.", confidence: 78 },
      { hypothesis: "Security policy becomes provider-neutral so switching AI models does not weaken identity, permission or audit guarantees.", confidence: 76 },
      { hypothesis: "Regulators, enterprise buyers and insurers increasingly request machine-readable evidence of agent controls and incident history.", confidence: 73 },
      { hypothesis: "Pantavion can evolve toward an Agent Immune System that combines identity, least privilege, behavioural monitoring, containment, recovery and evidence across the whole ecosystem.", confidence: 69 },
    ],
  },
  {
    id: "signal-youth-age-assurance-2026-08-27",
    title: "Youth safety is shifting from simple age gates to default product-level protections",
    summary:
      "Recent platform changes and legal pressure point toward age assurance, default teen protections, time/context limits, safer recommendation behaviour and auditable youth controls becoming product architecture rather than optional settings.",
    domain: "identity_age_assurance",
    eventType: "platform_policy",
    observedAt: "2026-08-27T00:00:00Z",
    jurisdictions: ["US", "GLOBAL"],
    productionRelevance: 88,
    humanBenefitPotential: 96,
    noveltyPotential: 78,
    riskIfIgnored: 90,
    reversibility: 84,
    evidence: [
      {
        title: "Time limits and a midnight cutoff: Meta's new rules for kids go further, but critics say not enough",
        publisher: "Associated Press",
        url: "https://apnews.com/article/8229962dac997f1b1557ce341c71b39d",
        publishedAt: "2026-08-27",
        tier: "reputable_wire",
      },
    ],
    foresightHypotheses: [
      { hypothesis: "Age assurance shifts from repeated raw identity checks toward privacy-preserving proofs that reveal only the minimum age fact needed.", confidence: 89 },
      { hypothesis: "Youth access evolves from a binary under/over threshold into progressive rights tied to age, jurisdiction and capability risk.", confidence: 91 },
      { hypothesis: "Safety defaults become contextual, including school hours, night hours, public/private communication and adult-contact risk.", confidence: 82 },
      { hypothesis: "Recommendation systems for minors are measured against child benefit and learning outcomes rather than time-on-platform alone.", confidence: 80 },
      { hypothesis: "Platforms expose transparent explanations for why youth users see content and give stronger control over personalization.", confidence: 77 },
      { hypothesis: "Regulators increasingly inspect product behaviour through age-specific test personas rather than relying only on written policies.", confidence: 78 },
      { hypothesis: "Country-specific youth rules compile into capability-level controls so legally permitted education/support can remain available even when public social functions are restricted.", confidence: 85 },
      { hypothesis: "Verified support networks become a required complement to automated safety systems when family or immediate environment cannot provide safe help.", confidence: 73 },
      { hypothesis: "Youth safety evidence becomes continuously auditable through measurable defaults, overrides, incidents, recommendation metrics and remediation history.", confidence: 74 },
      { hypothesis: "Pantavion can combine progressive age rights, curriculum learning, support routing, privacy-preserving age proofs and regulator simulation into a unified Youth Benefit Architecture.", confidence: 72 },
    ],
  },
  {
    id: "signal-eu-ai-act-enforcement-2026-08-27",
    title: "EU AI governance has moved from preparation into active enforcement infrastructure",
    summary:
      "The European Commission states that from 2 August 2026 the AI Office and national authorities are responsible for implementing, supervising and enforcing the AI Act, including powers related to GPAI models and corrective measures.",
    domain: "regulation_law",
    eventType: "law_or_regulation",
    observedAt: "2026-08-27T00:00:00Z",
    jurisdictions: ["EU"],
    productionRelevance: 91,
    humanBenefitPotential: 82,
    noveltyPotential: 68,
    riskIfIgnored: 95,
    reversibility: 74,
    evidence: [
      {
        title: "AI Act — Regulatory framework for AI",
        publisher: "European Commission",
        url: "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai",
        publishedAt: "2026-08",
        tier: "official_regulator",
      },
    ],
    foresightHypotheses: [
      { hypothesis: "Production systems need a continuously maintained inventory of AI capabilities, providers, purposes and jurisdictions rather than a one-time compliance document.", confidence: 94 },
      { hypothesis: "AI risk classification becomes executable policy metadata attached to each capability and workflow.", confidence: 90 },
      { hypothesis: "Provider-neutral routing must preserve regulatory obligations when a model or vendor changes.", confidence: 87 },
      { hypothesis: "Logs, model/provider identity, human overrides and material decisions increasingly need durable evidence suitable for regulator review.", confidence: 85 },
      { hypothesis: "High-impact AI changes require pre-deployment evidence packages combining technical tests, risk controls and governance sign-off.", confidence: 82 },
      { hypothesis: "External and third-party AI evaluation capacity grows, increasing demand for reproducible test surfaces and regulator-accessible sandboxes.", confidence: 79 },
      { hypothesis: "Country and regional legal differences move from documentation into policy-as-code capability matrices evaluated at runtime.", confidence: 88 },
      { hypothesis: "AI literacy, transparency and user-control obligations become product features that vary by role, age and context.", confidence: 76 },
      { hypothesis: "Compliance evidence becomes continuous and event-driven, generated when relevant code, models, policies or jurisdictions change.", confidence: 81 },
      { hypothesis: "Pantavion can evolve toward a Regulatory Digital Twin that simulates a capability for a specific country, age, role and AI provider before production activation.", confidence: 74 },
    ],
  },
];
