export type GlobalEmergencyLanguageDirection = "ltr" | "rtl";

export type GlobalEmergencyLanguageMeta = {
  code: GlobalEmergencyLanguage;
  label: string;
  nativeLabel: string;
  direction: GlobalEmergencyLanguageDirection;
};

export const globalEmergencyLanguages = [
  { code: "en", label: "English", nativeLabel: "English", direction: "ltr" },
  { code: "el", label: "Greek", nativeLabel: "Ελληνικά", direction: "ltr" },
  { code: "es", label: "Spanish", nativeLabel: "español", direction: "ltr" },
  { code: "fr", label: "French", nativeLabel: "français", direction: "ltr" },
  { code: "de", label: "German", nativeLabel: "Deutsch", direction: "ltr" },
  { code: "it", label: "Italian", nativeLabel: "italiano", direction: "ltr" },
  { code: "pt", label: "Portuguese", nativeLabel: "português", direction: "ltr" },
  { code: "ar", label: "Arabic", nativeLabel: "العربية", direction: "rtl" },
  { code: "tr", label: "Turkish", nativeLabel: "Türkçe", direction: "ltr" },
  { code: "ru", label: "Russian", nativeLabel: "русский", direction: "ltr" },
  { code: "zh", label: "Chinese", nativeLabel: "中文", direction: "ltr" },
  { code: "ja", label: "Japanese", nativeLabel: "日本語", direction: "ltr" },
  { code: "hi", label: "Hindi", nativeLabel: "हिन्दी", direction: "ltr" },
  { code: "bn", label: "Bangla", nativeLabel: "বাংলা", direction: "ltr" },
  { code: "ur", label: "Urdu", nativeLabel: "اردو", direction: "rtl" },
  { code: "fa", label: "Persian", nativeLabel: "فارسی", direction: "rtl" },
  { code: "he", label: "Hebrew", nativeLabel: "עברית", direction: "rtl" },
  { code: "sw", label: "Swahili", nativeLabel: "Kiswahili", direction: "ltr" },
  { code: "am", label: "Amharic", nativeLabel: "አማርኛ", direction: "ltr" },
  { code: "ha", label: "Hausa", nativeLabel: "Hausa", direction: "ltr" },
  { code: "yo", label: "Yoruba", nativeLabel: "Èdè Yorùbá", direction: "ltr" },
  { code: "ig", label: "Igbo", nativeLabel: "Igbo", direction: "ltr" },
  { code: "zu", label: "Zulu", nativeLabel: "isiZulu", direction: "ltr" },
  { code: "af", label: "Afrikaans", nativeLabel: "Afrikaans", direction: "ltr" },
  { code: "nl", label: "Dutch", nativeLabel: "Nederlands", direction: "ltr" },
  { code: "sv", label: "Swedish", nativeLabel: "svenska", direction: "ltr" },
  { code: "no", label: "Norwegian", nativeLabel: "norsk", direction: "ltr" },
  { code: "da", label: "Danish", nativeLabel: "dansk", direction: "ltr" },
  { code: "fi", label: "Finnish", nativeLabel: "suomi", direction: "ltr" },
  { code: "pl", label: "Polish", nativeLabel: "polski", direction: "ltr" },
  { code: "uk", label: "Ukrainian", nativeLabel: "українська", direction: "ltr" },
  { code: "ro", label: "Romanian", nativeLabel: "română", direction: "ltr" },
  { code: "bg", label: "Bulgarian", nativeLabel: "български", direction: "ltr" },
  { code: "sr", label: "Serbian", nativeLabel: "српски", direction: "ltr" },
  { code: "hr", label: "Croatian", nativeLabel: "hrvatski", direction: "ltr" },
  { code: "cs", label: "Czech", nativeLabel: "čeština", direction: "ltr" },
  { code: "sk", label: "Slovak", nativeLabel: "slovenčina", direction: "ltr" },
  { code: "hu", label: "Hungarian", nativeLabel: "magyar", direction: "ltr" },
  { code: "sq", label: "Albanian", nativeLabel: "shqip", direction: "ltr" },
  { code: "mk", label: "Macedonian", nativeLabel: "македонски", direction: "ltr" },
  { code: "sl", label: "Slovenian", nativeLabel: "slovenščina", direction: "ltr" },
  { code: "lt", label: "Lithuanian", nativeLabel: "lietuvių", direction: "ltr" },
  { code: "lv", label: "Latvian", nativeLabel: "latviešu", direction: "ltr" },
  { code: "et", label: "Estonian", nativeLabel: "eesti", direction: "ltr" },
  { code: "ka", label: "Georgian", nativeLabel: "ქართული", direction: "ltr" },
  { code: "hy", label: "Armenian", nativeLabel: "հայերեն", direction: "ltr" },
  { code: "az", label: "Azerbaijani", nativeLabel: "azərbaycan", direction: "ltr" },
  { code: "kk", label: "Kazakh", nativeLabel: "қазақ тілі", direction: "ltr" },
  { code: "uz", label: "Uzbek", nativeLabel: "o‘zbek", direction: "ltr" },
  { code: "mn", label: "Mongolian", nativeLabel: "монгол", direction: "ltr" },
  { code: "ko", label: "Korean", nativeLabel: "한국어", direction: "ltr" },
  { code: "th", label: "Thai", nativeLabel: "ไทย", direction: "ltr" },
  { code: "vi", label: "Vietnamese", nativeLabel: "Tiếng Việt", direction: "ltr" },
  { code: "id", label: "Indonesian", nativeLabel: "Indonesia", direction: "ltr" },
  { code: "ms", label: "Malay", nativeLabel: "Melayu", direction: "ltr" },
  { code: "fil", label: "Filipino", nativeLabel: "Filipino", direction: "ltr" },
  { code: "my", label: "Burmese", nativeLabel: "မြန်မာ", direction: "ltr" },
  { code: "km", label: "Khmer", nativeLabel: "ខ្មែរ", direction: "ltr" },
  { code: "lo", label: "Lao", nativeLabel: "ລາວ", direction: "ltr" },
  { code: "si", label: "Sinhala", nativeLabel: "සිංහල", direction: "ltr" },
  { code: "ne", label: "Nepali", nativeLabel: "नेपाली", direction: "ltr" },
  { code: "ta", label: "Tamil", nativeLabel: "தமிழ்", direction: "ltr" },
  { code: "te", label: "Telugu", nativeLabel: "తెలుగు", direction: "ltr" },
  { code: "ml", label: "Malayalam", nativeLabel: "മലയാളം", direction: "ltr" },
  { code: "kn", label: "Kannada", nativeLabel: "ಕನ್ನಡ", direction: "ltr" },
  { code: "mr", label: "Marathi", nativeLabel: "मराठी", direction: "ltr" },
  { code: "gu", label: "Gujarati", nativeLabel: "ગુજરાતી", direction: "ltr" },
  { code: "pa", label: "Punjabi", nativeLabel: "ਪੰਜਾਬੀ", direction: "ltr" },
  { code: "cy", label: "Welsh", nativeLabel: "Cymraeg", direction: "ltr" },
  { code: "ga", label: "Irish", nativeLabel: "Gaeilge", direction: "ltr" },
  { code: "is", label: "Icelandic", nativeLabel: "íslenska", direction: "ltr" },
  { code: "mt", label: "Maltese", nativeLabel: "Malti", direction: "ltr" },
  { code: "ca", label: "Catalan", nativeLabel: "català", direction: "ltr" },
  { code: "eu", label: "Basque", nativeLabel: "euskara", direction: "ltr" },
  { code: "gl", label: "Galician", nativeLabel: "galego", direction: "ltr" },
  { code: "be", label: "Belarusian", nativeLabel: "беларуская", direction: "ltr" },
  { code: "bs", label: "Bosnian", nativeLabel: "bosanski", direction: "ltr" },
  { code: "me", label: "me", nativeLabel: "me", direction: "ltr" },
  { code: "lb", label: "Luxembourgish", nativeLabel: "Lëtzebuergesch", direction: "ltr" },
  { code: "fo", label: "Faroese", nativeLabel: "føroyskt", direction: "ltr" },
  { code: "gd", label: "Scottish Gaelic", nativeLabel: "Gàidhlig", direction: "ltr" },
  { code: "kw", label: "Cornish", nativeLabel: "kernewek", direction: "ltr" },
  { code: "br", label: "Breton", nativeLabel: "brezhoneg", direction: "ltr" },
  { code: "oc", label: "Occitan", nativeLabel: "occitan", direction: "ltr" },
  { code: "co", label: "Corsican", nativeLabel: "Corsican", direction: "ltr" },
  { code: "fy", label: "Western Frisian", nativeLabel: "Frysk", direction: "ltr" },
  { code: "se", label: "Northern Sami", nativeLabel: "davvisámegiella", direction: "ltr" },
  { code: "smn", label: "Inari Sami", nativeLabel: "anarâškielâ", direction: "ltr" },
  { code: "sms", label: "Skolt Sami", nativeLabel: "Skolt Sami", direction: "ltr" },
  { code: "kl", label: "Kalaallisut", nativeLabel: "kalaallisut", direction: "ltr" },
  { code: "iu", label: "Inuktitut", nativeLabel: "Inuktitut", direction: "ltr" },
  { code: "cr", label: "Cree", nativeLabel: "Cree", direction: "ltr" },
  { code: "oj", label: "Ojibwa", nativeLabel: "Ojibwa", direction: "ltr" },
  { code: "mi", label: "Māori", nativeLabel: "Māori", direction: "ltr" },
  { code: "sm", label: "Samoan", nativeLabel: "Samoan", direction: "ltr" },
  { code: "to", label: "Tongan", nativeLabel: "lea fakatonga", direction: "ltr" },
  { code: "fj", label: "Fijian", nativeLabel: "Fijian", direction: "ltr" },
  { code: "haw", label: "Hawaiian", nativeLabel: "ʻŌlelo Hawaiʻi", direction: "ltr" },
  { code: "ty", label: "Tahitian", nativeLabel: "Tahitian", direction: "ltr" },
  { code: "mg", label: "Malagasy", nativeLabel: "Malagasy", direction: "ltr" },
  { code: "rw", label: "Kinyarwanda", nativeLabel: "Ikinyarwanda", direction: "ltr" },
  { code: "rn", label: "Rundi", nativeLabel: "Ikirundi", direction: "ltr" },
  { code: "ny", label: "Nyanja", nativeLabel: "Nyanja", direction: "ltr" },
  { code: "sn", label: "Shona", nativeLabel: "chiShona", direction: "ltr" },
  { code: "st", label: "Southern Sotho", nativeLabel: "Sesotho", direction: "ltr" },
  { code: "tn", label: "Tswana", nativeLabel: "Setswana", direction: "ltr" },
  { code: "ts", label: "Tsonga", nativeLabel: "Tsonga", direction: "ltr" },
  { code: "xh", label: "Xhosa", nativeLabel: "IsiXhosa", direction: "ltr" },
  { code: "ss", label: "Swati", nativeLabel: "Swati", direction: "ltr" },
  { code: "ve", label: "Venda", nativeLabel: "Venda", direction: "ltr" },
  { code: "nr", label: "South Ndebele", nativeLabel: "South Ndebele", direction: "ltr" },
  { code: "om", label: "Oromo", nativeLabel: "Oromoo", direction: "ltr" },
  { code: "ti", label: "Tigrinya", nativeLabel: "ትግርኛ", direction: "ltr" },
  { code: "so", label: "Somali", nativeLabel: "Soomaali", direction: "ltr" },
  { code: "aa", label: "Afar", nativeLabel: "Afar", direction: "ltr" },
  { code: "ak", label: "Akan", nativeLabel: "Akan", direction: "ltr" },
  { code: "tw", label: "Akan", nativeLabel: "Akan", direction: "ltr" },
  { code: "ee", label: "Ewe", nativeLabel: "eʋegbe", direction: "ltr" },
  { code: "ff", label: "Fula", nativeLabel: "Pulaar", direction: "ltr" },
  { code: "bm", label: "Bambara", nativeLabel: "bamanakan", direction: "ltr" },
  { code: "wo", label: "Wolof", nativeLabel: "Wolof", direction: "ltr" },
  { code: "dyu", label: "Dyula", nativeLabel: "Dyula", direction: "ltr" },
  { code: "ln", label: "Lingala", nativeLabel: "lingála", direction: "ltr" },
  { code: "kg", label: "Kongo", nativeLabel: "Kongo", direction: "ltr" },
  { code: "lu", label: "Luba-Katanga", nativeLabel: "Tshiluba", direction: "ltr" },
  { code: "lg", label: "Ganda", nativeLabel: "Luganda", direction: "ltr" },
  { code: "ki", label: "Kikuyu", nativeLabel: "Gikuyu", direction: "ltr" },
  { code: "rwk", label: "Rwa", nativeLabel: "Kiruwa", direction: "ltr" },
  { code: "asa", label: "Asu", nativeLabel: "Kipare", direction: "ltr" },
  { code: "bez", label: "Bena", nativeLabel: "Hibena", direction: "ltr" },
  { code: "ebu", label: "Embu", nativeLabel: "Kĩembu", direction: "ltr" },
  { code: "kam", label: "Kamba", nativeLabel: "Kikamba", direction: "ltr" },
  { code: "kln", label: "Kalenjin", nativeLabel: "Kalenjin", direction: "ltr" },
  { code: "luy", label: "Luyia", nativeLabel: "Luluhia", direction: "ltr" },
  { code: "mas", label: "Masai", nativeLabel: "Maa", direction: "ltr" },
  { code: "mer", label: "Meru", nativeLabel: "Kĩmĩrũ", direction: "ltr" },
  { code: "mfe", label: "Morisyen", nativeLabel: "kreol morisien", direction: "ltr" },
  { code: "naq", label: "Nama", nativeLabel: "Khoekhoegowab", direction: "ltr" },
  { code: "nd", label: "North Ndebele", nativeLabel: "isiNdebele", direction: "ltr" },
  { code: "nso", label: "Northern Sotho", nativeLabel: "Sesotho sa Leboa", direction: "ltr" },
  { code: "rof", label: "Rombo", nativeLabel: "Kihorombo", direction: "ltr" },
  { code: "saq", label: "Samburu", nativeLabel: "Kisampur", direction: "ltr" },
  { code: "seh", label: "Sena", nativeLabel: "sena", direction: "ltr" },
  { code: "teo", label: "Teso", nativeLabel: "Kiteso", direction: "ltr" },
  { code: "vai", label: "Vai", nativeLabel: "ꕙꔤ", direction: "ltr" },
  { code: "dje", label: "Zarma", nativeLabel: "Zarmaciine", direction: "ltr" },
  { code: "kab", label: "Kabyle", nativeLabel: "Taqbaylit", direction: "ltr" },
  { code: "shi", label: "Tachelhit", nativeLabel: "ⵜⴰⵛⵍⵃⵉⵜ", direction: "ltr" },
  { code: "tzm", label: "Central Atlas Tamazight", nativeLabel: "Tamaziɣt n laṭlaṣ", direction: "ltr" },
  { code: "zgh", label: "Standard Moroccan Tamazight", nativeLabel: "ⵜⴰⵎⴰⵣⵉⵖⵜ", direction: "ltr" },
  { code: "ber", label: "ber", nativeLabel: "ber", direction: "ltr" },
  { code: "ary", label: "Moroccan Arabic", nativeLabel: "Moroccan Arabic", direction: "ltr" },
  { code: "arz", label: "Egyptian Arabic", nativeLabel: "Egyptian Arabic", direction: "ltr" },
  { code: "ckb", label: "Central Kurdish", nativeLabel: "کوردیی ناوەندی", direction: "rtl" },
  { code: "ku", label: "Kurdish", nativeLabel: "kurdî (kurmancî)", direction: "ltr" },
  { code: "ps", label: "Pashto", nativeLabel: "پښتو", direction: "rtl" },
  { code: "sd", label: "Sindhi", nativeLabel: "سنڌي", direction: "rtl" },
  { code: "ks", label: "Kashmiri", nativeLabel: "کٲشُر", direction: "rtl" },
  { code: "dv", label: "Divehi", nativeLabel: "Divehi", direction: "rtl" },
  { code: "bal", label: "Baluchi", nativeLabel: "Baluchi", direction: "ltr" },
  { code: "bho", label: "Bhojpuri", nativeLabel: "भोजपुरी", direction: "ltr" },
  { code: "mai", label: "Maithili", nativeLabel: "मैथिली", direction: "ltr" },
  { code: "mag", label: "Magahi", nativeLabel: "Magahi", direction: "ltr" },
  { code: "sa", label: "Sanskrit", nativeLabel: "संस्कृत भाषा", direction: "ltr" },
  { code: "bo", label: "Tibetan", nativeLabel: "བོད་སྐད་", direction: "ltr" },
  { code: "dz", label: "Dzongkha", nativeLabel: "རྫོང་ཁ", direction: "ltr" },
  { code: "ug", label: "Uyghur", nativeLabel: "ئۇيغۇرچە", direction: "rtl" },
  { code: "ky", label: "Kyrgyz", nativeLabel: "кыргызча", direction: "ltr" },
  { code: "tg", label: "Tajik", nativeLabel: "тоҷикӣ", direction: "ltr" },
  { code: "tk", label: "Turkmen", nativeLabel: "türkmen dili", direction: "ltr" },
  { code: "tt", label: "Tatar", nativeLabel: "татар", direction: "ltr" },
  { code: "ba", label: "Bashkir", nativeLabel: "Bashkir", direction: "ltr" },
  { code: "cv", label: "Chuvash", nativeLabel: "чӑваш", direction: "ltr" },
  { code: "sah", label: "Yakut", nativeLabel: "саха тыла", direction: "ltr" },
  { code: "os", label: "Ossetic", nativeLabel: "ирон", direction: "ltr" },
  { code: "ce", label: "Chechen", nativeLabel: "нохчийн", direction: "ltr" },
  { code: "av", label: "Avaric", nativeLabel: "Avaric", direction: "ltr" },
  { code: "lez", label: "Lezghian", nativeLabel: "Lezghian", direction: "ltr" },
  { code: "ab", label: "Abkhazian", nativeLabel: "Abkhazian", direction: "ltr" },
  { code: "ady", label: "Adyghe", nativeLabel: "Adyghe", direction: "ltr" },
  { code: "kbd", label: "Kabardian", nativeLabel: "Kabardian", direction: "ltr" },
  { code: "dar", label: "Dargwa", nativeLabel: "Dargwa", direction: "ltr" },
  { code: "inh", label: "Ingush", nativeLabel: "Ingush", direction: "ltr" },
  { code: "kum", label: "Kumyk", nativeLabel: "Kumyk", direction: "ltr" },
  { code: "nog", label: "Nogai", nativeLabel: "Nogai", direction: "ltr" },
  { code: "rom", label: "Romany", nativeLabel: "Romany", direction: "ltr" },
  { code: "la", label: "Latin", nativeLabel: "Latin", direction: "ltr" },
  { code: "eo", label: "Esperanto", nativeLabel: "Esperanto", direction: "ltr" },
  { code: "ia", label: "Interlingua", nativeLabel: "interlingua", direction: "ltr" },
  { code: "ie", label: "Interlingue", nativeLabel: "Interlingue", direction: "ltr" },
  { code: "io", label: "Ido", nativeLabel: "Ido", direction: "ltr" },
  { code: "vo", label: "Volapük", nativeLabel: "Volapük", direction: "ltr" },
  { code: "jbo", label: "Lojban", nativeLabel: "Lojban", direction: "ltr" },
  { code: "lfn", label: "Lingua Franca Nova", nativeLabel: "Lingua Franca Nova", direction: "ltr" },
  { code: "avk", label: "Kotava", nativeLabel: "Kotava", direction: "ltr" },
  { code: "tok", label: "Toki Pona", nativeLabel: "toki pona", direction: "ltr" },
  { code: "tlh", label: "Klingon", nativeLabel: "Klingon", direction: "ltr" },
  { code: "na", label: "Nauru", nativeLabel: "Nauru", direction: "ltr" },
  { code: "bi", label: "Bislama", nativeLabel: "Bislama", direction: "ltr" },
  { code: "mh", label: "Marshallese", nativeLabel: "Marshallese", direction: "ltr" },
  { code: "pau", label: "Palauan", nativeLabel: "Palauan", direction: "ltr" },
  { code: "chk", label: "Chuukese", nativeLabel: "Chuukese", direction: "ltr" },
  { code: "pon", label: "Pohnpeian", nativeLabel: "Pohnpeian", direction: "ltr" },
  { code: "gil", label: "Gilbertese", nativeLabel: "Gilbertese", direction: "ltr" },
  { code: "kos", label: "Kosraean", nativeLabel: "Kosraean", direction: "ltr" },
  { code: "tet", label: "Tetum", nativeLabel: "Tetum", direction: "ltr" },
  { code: "bik", label: "Bikol", nativeLabel: "Bikol", direction: "ltr" },
  { code: "ceb", label: "Cebuano", nativeLabel: "Cebuano", direction: "ltr" },
  { code: "hil", label: "Hiligaynon", nativeLabel: "Hiligaynon", direction: "ltr" },
  { code: "ilo", label: "Iloko", nativeLabel: "Iloko", direction: "ltr" },
  { code: "war", label: "Waray", nativeLabel: "Waray", direction: "ltr" },
  { code: "pam", label: "Pampanga", nativeLabel: "Pampanga", direction: "ltr" },
  { code: "bcl", label: "Bikol", nativeLabel: "Bikol", direction: "ltr" },
  { code: "ace", label: "Acehnese", nativeLabel: "Acehnese", direction: "ltr" },
  { code: "ban", label: "Balinese", nativeLabel: "Balinese", direction: "ltr" },
  { code: "bug", label: "Buginese", nativeLabel: "Buginese", direction: "ltr" },
  { code: "jv", label: "Javanese", nativeLabel: "Jawa", direction: "ltr" },
  { code: "su", label: "Sundanese", nativeLabel: "Basa Sunda", direction: "ltr" },
  { code: "mad", label: "Madurese", nativeLabel: "Madurese", direction: "ltr" },
  { code: "min", label: "Minangkabau", nativeLabel: "Minangkabau", direction: "ltr" },
  { code: "gor", label: "Gorontalo", nativeLabel: "Gorontalo", direction: "ltr" },
  { code: "mak", label: "Makasar", nativeLabel: "Makasar", direction: "ltr" },
  { code: "sas", label: "Sasak", nativeLabel: "Sasak", direction: "ltr" },
  { code: "bjn", label: "Banjar", nativeLabel: "Banjar", direction: "ltr" },
  { code: "pag", label: "Pangasinan", nativeLabel: "Pangasinan", direction: "ltr" },
  { code: "hmn", label: "Hmong", nativeLabel: "Hmong", direction: "ltr" },
  { code: "brx", label: "Bodo", nativeLabel: "बर’", direction: "ltr" },
  { code: "mni", label: "Manipuri", nativeLabel: "মৈতৈলোন্", direction: "ltr" },
  { code: "sat", label: "Santali", nativeLabel: "ᱥᱟᱱᱛᱟᱲᱤ", direction: "ltr" },
  { code: "doi", label: "Dogri", nativeLabel: "डोगरी", direction: "ltr" },
  { code: "kok", label: "Konkani", nativeLabel: "कोंकणी", direction: "ltr" },
  { code: "ksw", label: "ksw", nativeLabel: "ksw", direction: "ltr" },
  { code: "lus", label: "Mizo", nativeLabel: "Mizo", direction: "ltr" },
  { code: "kha", label: "Khasi", nativeLabel: "Khasi", direction: "ltr" },
  { code: "npi", label: "Nepali", nativeLabel: "नेपाली", direction: "ltr" },
  { code: "new", label: "Newari", nativeLabel: "Newari", direction: "ltr" },
  { code: "raj", label: "Rajasthani", nativeLabel: "राजस्थानी", direction: "ltr" },
  { code: "awa", label: "Awadhi", nativeLabel: "Awadhi", direction: "ltr" },
  { code: "hne", label: "hne", nativeLabel: "hne", direction: "ltr" },
  { code: "gbm", label: "gbm", nativeLabel: "gbm", direction: "ltr" },
  { code: "unr", label: "unr", nativeLabel: "unr", direction: "ltr" },
  { code: "hoc", label: "hoc", nativeLabel: "hoc", direction: "ltr" },
  { code: "lif", label: "lif", nativeLabel: "lif", direction: "ltr" },
  { code: "lep", label: "lep", nativeLabel: "lep", direction: "ltr" },
  { code: "grt", label: "grt", nativeLabel: "grt", direction: "ltr" },
  { code: "tcy", label: "Tulu", nativeLabel: "Tulu", direction: "ltr" },
  { code: "sol", label: "sol", nativeLabel: "sol", direction: "ltr" },
  { code: "rap", label: "Rapanui", nativeLabel: "Rapanui", direction: "ltr" },
  { code: "qu", label: "Quechua", nativeLabel: "Runasimi", direction: "ltr" },
  { code: "ay", label: "Aymara", nativeLabel: "Aymara", direction: "ltr" },
  { code: "gn", label: "Guarani", nativeLabel: "Guarani", direction: "ltr" },
  { code: "ht", label: "Haitian Creole", nativeLabel: "Haitian Creole", direction: "ltr" },
  { code: "pap", label: "Papiamento", nativeLabel: "Papiamento", direction: "ltr" },
  { code: "nah", label: "nah", nativeLabel: "nah", direction: "ltr" },
  { code: "arn", label: "Mapuche", nativeLabel: "Mapuche", direction: "ltr" },
  { code: "map", label: "map", nativeLabel: "map", direction: "ltr" },
  { code: "chr", label: "Cherokee", nativeLabel: "ᏣᎳᎩ", direction: "ltr" },
  { code: "lkt", label: "Lakota", nativeLabel: "Lakȟólʼiyapi", direction: "ltr" },
  { code: "nv", label: "Navajo", nativeLabel: "Navajo", direction: "ltr" },
  { code: "yua", label: "yua", nativeLabel: "yua", direction: "ltr" },
] as const;

export type GlobalEmergencyLanguage =
  (typeof globalEmergencyLanguages)[number]["code"];

export const globalEmergencyLanguageCodes = globalEmergencyLanguages.map(
  (language) => language.code
) as GlobalEmergencyLanguage[];

const globalEmergencyLanguageAliases: Record<string, GlobalEmergencyLanguage> = {
  "pt-br": "pt",
  "pt-pt": "pt",
  "zh-cn": "zh",
  "zh-hans": "zh",
  "zh-hant": "zh",
  "zh-tw": "zh",
  "nb": "no",
  "nn": "no",
  "iw": "he",
  "tl": "fil",
};

export function normalizeGlobalEmergencyLanguage(
  language?: string | null
): GlobalEmergencyLanguage {
  const value = (language ?? "en").toLowerCase();

  if (value in globalEmergencyLanguageAliases) {
    return globalEmergencyLanguageAliases[value];
  }

  const base = value.split("-")[0];

  if (base in globalEmergencyLanguageAliases) {
    return globalEmergencyLanguageAliases[base];
  }

  const direct = globalEmergencyLanguageCodes.find(
    (code) => value === code || value.startsWith(code + "-")
  );

  return direct ?? "en";
}
