import type {
  PantavionSosDevice,
  PantavionSosLocation,
  PantavionSosPacket,
  PantavionSosProfile,
} from "@/types/pantavion-sos";

const PROFILE_KEY = "pantavion.sos.profile.v1";
const QUEUE_KEY = "pantavion.sos.queue.v1";

export function createPantavionId(prefix: string) {
  return (
    prefix +
    "-" +
    Date.now().toString(36) +
    "-" +
    Math.random().toString(36).slice(2, 10)
  );
}

export function createDefaultSosProfile(): PantavionSosProfile {
  return {
    fullName: "",
    primaryLanguage: "en",
    emergencyNumber:
      process.env.NEXT_PUBLIC_PANTAVION_DEFAULT_EMERGENCY_NUMBER || "112",
    medicalNotes: "",
    allergies: "",
    bloodType: "",
    contacts: [],
    consent: false,
    updatedAt: new Date().toISOString(),
  };
}

export function loadSosProfile(): PantavionSosProfile {
  if (typeof window === "undefined") return createDefaultSosProfile();

  try {
    const raw = window.localStorage.getItem(PROFILE_KEY);
    if (!raw) return createDefaultSosProfile();

    const parsed = JSON.parse(raw) as Partial<PantavionSosProfile>;

    return {
      ...createDefaultSosProfile(),
      ...parsed,
      contacts: Array.isArray(parsed.contacts) ? parsed.contacts : [],
      updatedAt: parsed.updatedAt || new Date().toISOString(),
    };
  } catch {
    return createDefaultSosProfile();
  }
}

export function saveSosProfile(profile: PantavionSosProfile) {
  if (typeof window === "undefined") return;

  window.localStorage.setItem(
    PROFILE_KEY,
    JSON.stringify({
      ...profile,
      updatedAt: new Date().toISOString(),
    })
  );
}

export function loadSosQueue(): PantavionSosPacket[] {
  if (typeof window === "undefined") return [];

  try {
    const raw = window.localStorage.getItem(QUEUE_KEY);
    if (!raw) return [];

    const parsed = JSON.parse(raw) as PantavionSosPacket[];
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

export function saveSosQueue(queue: PantavionSosPacket[]) {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(QUEUE_KEY, JSON.stringify(queue));
}

export function queueSosPacket(packet: PantavionSosPacket) {
  const queue = loadSosQueue();
  queue.push(packet);
  saveSosQueue(queue);
}

export function createDeviceSnapshot(): PantavionSosDevice {
  if (typeof window === "undefined") {
    return {
      userAgent: "server",
      platform: "server",
      language: "unknown",
      online: false,
      screen: "unknown",
      timestamp: new Date().toISOString(),
    };
  }

  return {
    userAgent: window.navigator.userAgent,
    platform: window.navigator.platform,
    language: window.navigator.language,
    online: window.navigator.onLine,
    screen: `${window.screen.width}x${window.screen.height}`,
    timestamp: new Date().toISOString(),
  };
}

export function buildSosMessage(
  profile: PantavionSosProfile,
  location: PantavionSosLocation | null,
  device: PantavionSosDevice
) {
  const contactLines =
    profile.contacts.length > 0
      ? profile.contacts
          .map((contact, index) => {
            return `${index + 1}. ${contact.name || "Unnamed contact"} | phone: ${
              contact.phone || "not set"
            } | email: ${contact.email || "not set"} | relation: ${
              contact.relation || "not set"
            }`;
          })
          .join("\n")
      : "No emergency contacts saved.";

  const locationLine = location
    ? `${location.lat}, ${location.lng} | accuracy: ${
        location.accuracy ?? "unknown"
      }m | timestamp: ${location.timestamp}`
    : "Location unavailable or not permitted yet.";

  return [
    "PANTAVION LIFESHIELD SOS",
    "STATUS: HUMAN EMERGENCY ALERT",
    "",
    `Name: ${profile.fullName || "not set"}`,
    `Primary language: ${profile.primaryLanguage || "not set"}`,
    `Emergency number: ${profile.emergencyNumber || "not set"}`,
    `Blood type: ${profile.bloodType || "not set"}`,
    `Medical notes: ${profile.medicalNotes || "none provided"}`,
    `Allergies: ${profile.allergies || "none provided"}`,
    "",
    "Emergency contacts:",
    contactLines,
    "",
    `Location: ${locationLine}`,
    "",
    `Device online: ${device.online ? "yes" : "no"}`,
    `Device platform: ${device.platform}`,
    `Device language: ${device.language}`,
    `Created: ${new Date().toISOString()}`,
    "",
    "This SOS was generated by Pantavion LifeShield. It does not replace official emergency services. Use local emergency numbers immediately where possible.",
  ].join("\n");
}

export function createSosPacket(
  profile: PantavionSosProfile,
  location: PantavionSosLocation | null,
  offlineQueued: boolean
): PantavionSosPacket {
  const device = createDeviceSnapshot();

  return {
    id: createPantavionId("sos"),
    createdAt: new Date().toISOString(),
    source: "pantavion-web-pwa",
    status: "active",
    profile,
    location,
    device,
    message: buildSosMessage(profile, location, device),
    offlineQueued,
    deliveryAttempts: 0,
  };
}
