"use client";

import Link from "next/link";
import { ChangeEvent, FormEvent, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Contact = { id: string; display_name: string | null; email: string | null; phone: string | null; linked_user_id: string | null; source_external_id: string | null; created_at: string };
type ParsedContact = { display_name: string | null; email: string | null; phone: string | null };
type DiscoveryMatch = { user_id: string; display_name: string | null; avatar_url: string | null; country_code: string | null; region: string | null; city: string | null; matched_by: "email" | "phone" };

function parseVCard(text: string): ParsedContact[] { return text.split(/END:VCARD/i).map((chunk) => ({ display_name: chunk.match(/(?:^|\n)FN[^:]*:(.+)/i)?.[1]?.trim() ?? null, email: chunk.match(/(?:^|\n)EMAIL[^:]*:(.+)/i)?.[1]?.trim() ?? null, phone: chunk.match(/(?:^|\n)TEL[^:]*:(.+)/i)?.[1]?.trim() ?? null })).filter((item) => item.display_name || item.email || item.phone); }
function parseCsv(text: string): ParsedContact[] { const rows=text.split(/\r?\n/).map((r)=>r.trim()).filter(Boolean); if(!rows.length)return[]; const headers=rows[0].split(",").map((h)=>h.trim().toLowerCase()); const idx=(names:string[])=>headers.findIndex((h)=>names.includes(h)); const ni=idx(["name","display_name","full name","fullname"]), ei=idx(["email","e-mail"]), pi=idx(["phone","mobile","telephone","tel"]); return rows.slice(1).map((row)=>{const c=row.split(",").map((x)=>x.trim().replace(/^"|"$/g,"")); return {display_name:ni>=0?c[ni]||null:null,email:ei>=0?c[ei]||null:null,phone:pi>=0?c[pi]||null:null};}).filter((i)=>i.display_name||i.email||i.phone); }

export default function ContactsClient({ initialContacts, backendReady }: { initialContacts: Contact[]; backendReady: boolean }) {
 const supabase=useMemo(()=>createClient(),[]); const [contacts,setContacts]=useState(initialContacts); const [matches,setMatches]=useState<DiscoveryMatch[]>([]); const [message,setMessage]=useState(backendReady?"":"Η βάση επαφών δεν είναι ακόμη διαθέσιμη στο production."); const [busy,setBusy]=useState(false);
 async function refresh(){const {data}=await supabase.from("contacts").select("id,display_name,email,phone,linked_user_id,source_external_id,created_at").order("display_name"); if(data)setContacts(data as Contact[]);}
 async function addManual(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);const {error}=await supabase.rpc("pantavion_add_manual_contact",{p_display_name:String(form.get("name")||"").trim()||null,p_email:String(form.get("email")||"").trim()||null,p_phone:String(form.get("phone")||"").trim()||null});setBusy(false);if(error)return setMessage(error.message);event.currentTarget.reset();await refresh();}
 async function importFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setBusy(true);setMessage("");try{const text=await file.text();const isVcard=file.name.toLowerCase().endsWith(".vcf");const parsed=isVcard?parseVCard(text):parseCsv(text);if(!parsed.length){setMessage("Δεν βρέθηκαν επαφές στο αρχείο.");return;}const {data,error}=await supabase.rpc("pantavion_import_contacts_batch",{p_source_type:isVcard?"vcard":"csv",p_filename:file.name,p_contacts:parsed});if(error){setMessage(error.message);return;}setMessage(`Μεταφέρθηκαν ${Number(data??0)} επαφές.`);event.target.value="";await refresh();}finally{setBusy(false);}}
 async function findMyPeople(){if(!contacts.length||busy)return;setBusy(true);setMessage("");setMatches([]);try{const response=await fetch("/api/people/find-from-contacts",{method:"POST"});const json=await response.json().catch(()=>({}));if(!response.ok){setMessage(json.detail||"Δεν ολοκληρώθηκε η αναζήτηση.");return;}const found=(json.matches??[]) as DiscoveryMatch[];setMatches(found);setMessage(found.length?`Βρέθηκαν ${found.length} επαφές που είναι ήδη στο Pantavion.`:"Δεν βρέθηκε ακόμη κάποια από αυτές τις επαφές στο Pantavion.");}finally{setBusy(false);}}
 return <div className="grid gap-5 lg:grid-cols-[340px_1fr]">
  <aside className="rounded-[1.4rem] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black text-[#173f72]">Προσθήκη επαφών</h2><form className="mt-4 space-y-3" onSubmit={addManual}><input name="name" placeholder="Όνομα" className="w-full rounded-xl border border-slate-200 px-3 py-2.5"/><input name="email" type="email" placeholder="Email" className="w-full rounded-xl border border-slate-200 px-3 py-2.5"/><input name="phone" placeholder="Τηλέφωνο" className="w-full rounded-xl border border-slate-200 px-3 py-2.5"/><button disabled={busy||!backendReady} className="w-full rounded-full bg-[#2467aa] px-4 py-2.5 text-sm font-black text-white disabled:opacity-40">Προσθήκη</button></form><div className="my-5 h-px bg-slate-100"/><label className="block text-sm font-black text-slate-700">Μεταφορά από αρχείο</label><p className="mt-1 text-xs leading-5 text-slate-500">vCard (.vcf) ή CSV που έχεις εξαγάγει εσύ από συσκευή ή υπηρεσία.</p><input className="mt-3 block w-full text-xs" type="file" accept=".vcf,.csv,text/vcard,text/csv" disabled={busy||!backendReady} onChange={importFile}/><div className="my-5 h-px bg-slate-100"/><h3 className="text-sm font-black text-slate-800">Βρες τους ανθρώπους σου</h3><p className="mt-1 text-xs leading-5 text-slate-500">Με δική σου επιλογή γίνεται ιδιωτικό matching. Δεν εμφανίζονται email ή τηλέφωνα άλλων χρηστών.</p><button type="button" disabled={busy||!backendReady||!contacts.length} onClick={findMyPeople} className="mt-3 w-full rounded-full bg-[#123b67] px-4 py-2.5 text-sm font-black text-white disabled:opacity-40">{busy?"Εργασία…":"Βρες φίλους στο Pantavion"}</button>{message&&<p className="mt-4 rounded-xl bg-slate-50 p-3 text-xs font-semibold text-slate-700">{message}</p>}</aside>
  <section className="space-y-5">{matches.length>0&&<div className="rounded-[1.4rem] border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-xl font-black text-[#173f72]">Άνθρωποι που βρέθηκαν</h2><div className="mt-4 divide-y divide-slate-100">{matches.map((m)=><div key={`${m.user_id}:${m.matched_by}`} className="flex items-center justify-between gap-3 py-3"><div><p className="font-black text-slate-900">{m.display_name||"Pantavion user"}</p><p className="text-xs text-slate-500">{[m.city,m.region,m.country_code].filter(Boolean).join(" · ")} · match: {m.matched_by}</p></div><Link href="/people" className="rounded-full bg-[#2467aa] px-3 py-2 text-[10px] font-black text-white no-underline">Άνοιγμα</Link></div>)}</div></div>}<div className="rounded-[1.4rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-black text-[#173f72]">Οι επαφές μου</h2><span className="text-xs font-black text-slate-400">{contacts.length}</span></div><div className="mt-4 divide-y divide-slate-100">{contacts.map((c)=><div key={c.id} className="py-3"><p className="truncate font-black text-slate-900">{c.display_name||c.email||c.phone||"Επαφή"}</p><p className="truncate text-xs text-slate-500">{[c.email,c.phone].filter(Boolean).join(" · ")}</p></div>)}{!contacts.length&&<p className="py-8 text-sm text-slate-500">Δεν έχεις μεταφέρει ακόμη επαφές.</p>}</div></div></section>
 </div>;
}
