-- Pantavion Water PostGIS + MVT foundation
-- Canonical rule: the authentic source/master stays immutable.
-- These tables contain web-optimized derived GIS objects only.

create extension if not exists postgis with schema extensions;

create table if not exists public.water_gis_import_jobs (
  job_id uuid primary key default gen_random_uuid(),
  source_id uuid null references public.water_map_ingest_catalog(source_id) on delete restrict,
  map_id text not null,
  source_format text not null,
  source_sha256 text null,
  source_storage_bucket text null,
  source_storage_path text null,
  pipeline_id text not null default 'pantavion-gis-importer',
  pipeline_version text not null default 'v1',
  status text not null default 'queued',
  detected_crs text null,
  output_crs text not null default 'EPSG:4326',
  feature_count bigint not null default 0,
  invalid_geometry_count bigint not null default 0,
  topology_state text not null default 'pending',
  tile_state text not null default 'pending',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  started_at timestamptz null,
  completed_at timestamptz null,
  updated_at timestamptz not null default now(),
  constraint water_gis_import_jobs_status_check
    check (status in ('queued','processing','review_required','ready','failed')),
  constraint water_gis_import_jobs_map_id_check
    check (length(trim(map_id)) > 0)
);

create table if not exists public.water_gis_features (
  feature_id bigint generated by default as identity primary key,
  import_job_id uuid null references public.water_gis_import_jobs(job_id) on delete restrict,
  map_id text not null,
  source_kind text not null,
  source_table text null,
  source_feature_id text not null,
  source_sha256 text null,
  object_class text not null default 'network-object',
  layer_name text null,
  name text null,
  style_url text null,
  properties jsonb not null default '{}'::jsonb,
  geom extensions.geometry(Geometry, 4326) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (map_id, source_kind, source_feature_id)
);

create index if not exists water_gis_features_geom_gist
  on public.water_gis_features using gist (geom);
create index if not exists water_gis_features_map_id_feature_id_idx
  on public.water_gis_features (map_id, feature_id);
create index if not exists water_gis_features_object_class_idx
  on public.water_gis_features (map_id, object_class);
create index if not exists water_gis_features_layer_name_idx
  on public.water_gis_features (map_id, layer_name);
create index if not exists water_gis_features_import_job_id_idx
  on public.water_gis_features (import_job_id);
create index if not exists water_gis_import_jobs_source_id_idx
  on public.water_gis_import_jobs (source_id);

create table if not exists public.water_network_nodes (
  node_id bigint generated by default as identity primary key,
  map_id text not null,
  node_key text not null,
  node_class text not null default 'junction',
  geom extensions.geometry(Point, 4326) not null,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (map_id, node_key)
);

create index if not exists water_network_nodes_geom_gist
  on public.water_network_nodes using gist (geom);

create table if not exists public.water_network_edges (
  edge_id bigint generated by default as identity primary key,
  map_id text not null,
  feature_id bigint not null references public.water_gis_features(feature_id) on delete restrict,
  from_node_id bigint null references public.water_network_nodes(node_id) on delete restrict,
  to_node_id bigint null references public.water_network_nodes(node_id) on delete restrict,
  edge_class text not null default 'pipe',
  connectivity_state text not null default 'unresolved',
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (map_id, feature_id)
);

create index if not exists water_network_edges_from_node_idx
  on public.water_network_edges (map_id, from_node_id);
create index if not exists water_network_edges_to_node_idx
  on public.water_network_edges (map_id, to_node_id);
create index if not exists water_network_edges_feature_id_idx
  on public.water_network_edges (feature_id);
create index if not exists water_network_edges_from_node_id_idx
  on public.water_network_edges (from_node_id);
create index if not exists water_network_edges_to_node_id_idx
  on public.water_network_edges (to_node_id);

alter table public.water_gis_import_jobs enable row level security;
alter table public.water_gis_features enable row level security;
alter table public.water_network_nodes enable row level security;
alter table public.water_network_edges enable row level security;

revoke all on table public.water_gis_import_jobs from anon, authenticated;
revoke all on table public.water_gis_features from anon, authenticated;
revoke all on table public.water_network_nodes from anon, authenticated;
revoke all on table public.water_network_edges from anon, authenticated;

grant all on table public.water_gis_import_jobs to service_role;
grant all on table public.water_gis_features to service_role;
grant all on table public.water_network_nodes to service_role;
grant all on table public.water_network_edges to service_role;
grant usage, select on sequence public.water_gis_features_feature_id_seq to service_role;
grant usage, select on sequence public.water_network_nodes_node_id_seq to service_role;
grant usage, select on sequence public.water_network_edges_edge_id_seq to service_role;

-- Materialize the already verified Map A derivative into PostGIS.
-- ST_Force2D is intentionally applied only to the web derivative; it never
-- modifies the original DWG/KMZ master or its preserved source bytes.
insert into public.water_gis_import_jobs (
  map_id,
  source_format,
  source_sha256,
  pipeline_id,
  pipeline_version,
  status,
  detected_crs,
  output_crs,
  feature_count,
  invalid_geometry_count,
  topology_state,
  tile_state,
  metadata,
  started_at,
  completed_at
)
select
  'A',
  'KMZ-derived-from-DWG',
  (
    select source_sha256
    from public.water_map_a_live_features_full
    where source_sha256 is not null
    group by source_sha256
    order by count(*) desc
    limit 1
  ),
  'pantavion-map-a-existing-derived-import',
  'v1',
  'ready',
  'EPSG:4326',
  'EPSG:4326',
  (select count(*)::bigint
   from public.water_map_a_live_features_full
   where feature ? 'geometry'),
  11,
  'pending',
  'ready',
  jsonb_build_object(
    'sourceTable','water_map_a_live_features_full',
    'masterPolicy','immutable',
    'canonicalAuthority','pantavion',
    'webGeometry','2D derived via ST_Force2D; original master unchanged',
    'note','Spatialized web-optimized derivative. Original master is unchanged.'
  ),
  now(),
  now()
where not exists (
  select 1
  from public.water_gis_import_jobs j
  where j.map_id='A'
    and j.pipeline_id='pantavion-map-a-existing-derived-import'
);

insert into public.water_gis_features (
  import_job_id,
  map_id,
  source_kind,
  source_table,
  source_feature_id,
  source_sha256,
  object_class,
  layer_name,
  name,
  style_url,
  properties,
  geom
)
select
  j.job_id,
  'A',
  'derived-kmz',
  'water_map_a_live_features_full',
  f.id::text,
  f.source_sha256,
  case
    when f.feature->'geometry'->>'type' in ('LineString','MultiLineString')
      then 'pipe'
    else 'network-object'
  end,
  nullif(
    substring(
      coalesce(f.feature->'properties'->>'description','')
      from 'Layer (.*?) LyrFrzn'
    ),
    ''
  ),
  nullif(f.feature->'properties'->>'name',''),
  nullif(f.feature->'properties'->>'styleUrl',''),
  coalesce(f.feature->'properties','{}'::jsonb),
  extensions.st_force2d(
    extensions.st_makevalid(
      extensions.st_setsrid(
        extensions.st_geomfromgeojson((f.feature->'geometry')::text),
        4326
      )
    )
  )
from public.water_map_a_live_features_full f
cross join lateral (
  select job_id
  from public.water_gis_import_jobs
  where map_id='A'
    and pipeline_id='pantavion-map-a-existing-derived-import'
  order by created_at desc
  limit 1
) j
where f.feature ? 'geometry'
on conflict (map_id, source_kind, source_feature_id) do nothing;

insert into public.water_network_edges (
  map_id,
  feature_id,
  edge_class,
  connectivity_state,
  properties
)
select
  map_id,
  feature_id,
  'pipe',
  'unresolved',
  jsonb_build_object(
    'layerName', layer_name,
    'sourceFeatureId', source_feature_id
  )
from public.water_gis_features
where map_id='A'
  and object_class='pipe'
on conflict (map_id, feature_id) do nothing;

-- Provider-neutral bbox Feature API primitive. Server-only.
create or replace function public.pantavion_water_features_bbox_internal_v1(
  p_map_id text,
  p_min_lng double precision,
  p_min_lat double precision,
  p_max_lng double precision,
  p_max_lat double precision,
  p_max_features integer default 2000
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_limit integer;
  v_bbox extensions.geometry;
  v_features jsonb;
  v_count integer;
  v_truncated boolean;
begin
  if p_min_lng is null or p_min_lat is null
     or p_max_lng is null or p_max_lat is null
     or p_min_lng >= p_max_lng or p_min_lat >= p_max_lat
     or p_min_lng < -180 or p_max_lng > 180
     or p_min_lat < -90 or p_max_lat > 90 then
    raise exception 'invalid_bbox';
  end if;

  v_limit := greatest(1, least(coalesce(p_max_features,2000),5000));
  v_bbox := extensions.st_makeenvelope(
    p_min_lng,p_min_lat,p_max_lng,p_max_lat,4326
  );

  with matched as (
    select
      f.feature_id,
      f.object_class,
      f.layer_name,
      f.name,
      f.style_url,
      f.source_feature_id,
      f.geom
    from public.water_gis_features f
    where f.map_id = upper(trim(p_map_id))
      and extensions.st_intersects(f.geom, v_bbox)
    order by f.feature_id
    limit v_limit + 1
  ),
  limited as (
    select * from matched limit v_limit
  )
  select
    coalesce(
      jsonb_agg(
        jsonb_build_object(
          'type','Feature',
          'id',feature_id,
          'geometry',extensions.st_asgeojson(geom)::jsonb,
          'properties',jsonb_strip_nulls(jsonb_build_object(
            'featureId',feature_id,
            'sourceFeatureId',source_feature_id,
            'objectClass',object_class,
            'layerName',layer_name,
            'name',name,
            'styleUrl',style_url
          ))
        )
        order by feature_id
      ),
      '[]'::jsonb
    ),
    (select count(*) from matched),
    (select count(*) > v_limit from matched)
  into v_features, v_count, v_truncated
  from limited;

  return jsonb_build_object(
    'status','segment_ready',
    'segment',jsonb_build_object(
      'type','FeatureCollection',
      'features',coalesce(v_features,'[]'::jsonb)
    ),
    'segmentCount',least(coalesce(v_count,0),v_limit),
    'segmentTruncated',coalesce(v_truncated,false),
    'dataReturned',true,
    'segmentReturned',true,
    'completeNetworkReturned',false,
    'rawMasterReturned',false,
    'browserFullNetworkLoaded',false,
    'source','pantavion-postgis-v1'
  );
end;
$function$;

-- Provider-neutral Mapbox Vector Tile primitive. The API boundary authorizes
-- the request before invoking this service-role-only function.
create or replace function public.pantavion_water_mvt_tile_internal_v1(
  p_map_id text,
  p_z integer,
  p_x integer,
  p_y integer
)
returns text
language plpgsql
security invoker
set search_path = ''
as $function$
declare
  v_tile extensions.geometry;
  v_bbox4326 extensions.geometry;
  v_limit integer;
  v_mvt bytea;
begin
  if p_z is null or p_x is null or p_y is null
     or p_z < 0 or p_z > 22
     or p_x < 0 or p_y < 0
     or p_x >= (1::bigint << p_z)
     or p_y >= (1::bigint << p_z) then
    raise exception 'invalid_tile';
  end if;

  if p_z < 12 then
    return '';
  end if;

  v_limit := case
    when p_z <= 12 then 2500
    when p_z <= 14 then 6000
    when p_z <= 16 then 12000
    else 24000
  end;

  v_tile := extensions.st_tileenvelope(p_z,p_x,p_y);
  v_bbox4326 := extensions.st_transform(v_tile,4326);

  with tile_rows as (
    select
      f.feature_id::bigint as id,
      f.object_class,
      f.layer_name,
      f.name,
      f.style_url,
      f.source_feature_id,
      extensions.st_asmvtgeom(
        extensions.st_transform(f.geom,3857),
        v_tile,
        4096,
        64,
        true
      ) as geom
    from public.water_gis_features f
    where f.map_id = upper(trim(p_map_id))
      and extensions.st_intersects(f.geom,v_bbox4326)
    order by f.feature_id
    limit v_limit
  )
  select extensions.st_asmvt(tile_rows,'water',4096,'geom','id')
  into v_mvt
  from tile_rows
  where geom is not null;

  return encode(coalesce(v_mvt,''::bytea),'base64');
end;
$function$;

revoke all on function public.pantavion_water_features_bbox_internal_v1(
  text,double precision,double precision,double precision,double precision,integer
) from public, anon, authenticated;

revoke all on function public.pantavion_water_mvt_tile_internal_v1(
  text,integer,integer,integer
) from public, anon, authenticated;

grant execute on function public.pantavion_water_features_bbox_internal_v1(
  text,double precision,double precision,double precision,double precision,integer
) to service_role;

grant execute on function public.pantavion_water_mvt_tile_internal_v1(
  text,integer,integer,integer
) to service_role;
