create table public.interpreter_sessions (
  id uuid primary key default gen_random_uuid(),
  created_by uuid not null references auth.users(id) on delete cascade,
  language_a text not null,
  language_b text not null,
  status text not null default 'pairing' check (status in ('pairing','active','closed','expired')),
  pairing_code_hash text unique,
  pairing_expires_at timestamptz not null default (now() + interval '15 minutes'),
  expires_at timestamptz not null default (now() + interval '2 hours'),
  paired_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (char_length(language_a) between 2 and 35),
  check (char_length(language_b) between 2 and 35),
  check (lower(language_a) <> lower(language_b)),
  check (pairing_expires_at <= expires_at),
  check (expires_at > created_at)
);

create index interpreter_sessions_created_by_idx
  on public.interpreter_sessions(created_by, created_at desc);
create index interpreter_sessions_active_expiry_idx
  on public.interpreter_sessions(status, expires_at)
  where status in ('pairing','active');

create table public.interpreter_session_members (
  session_id uuid not null references public.interpreter_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('host','guest')),
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  primary key (session_id, user_id)
);

create unique index interpreter_session_one_host_idx
  on public.interpreter_session_members(session_id)
  where role = 'host' and left_at is null;
create unique index interpreter_session_one_guest_idx
  on public.interpreter_session_members(session_id)
  where role = 'guest' and left_at is null;
create index interpreter_session_members_user_idx
  on public.interpreter_session_members(user_id, joined_at desc)
  where left_at is null;

create table public.interpreter_pairing_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  attempted_at timestamptz not null default now(),
  success boolean not null default false,
  session_id uuid references public.interpreter_sessions(id) on delete set null
);

create index interpreter_pairing_attempts_user_time_idx
  on public.interpreter_pairing_attempts(user_id, attempted_at desc);

alter table public.interpreter_sessions enable row level security;
alter table public.interpreter_session_members enable row level security;
alter table public.interpreter_pairing_attempts enable row level security;

grant select on public.interpreter_sessions to authenticated;
grant select on public.interpreter_session_members to authenticated;
revoke all on public.interpreter_pairing_attempts from anon, authenticated;
revoke insert, update, delete on public.interpreter_sessions from anon, authenticated;
revoke insert, update, delete on public.interpreter_session_members from anon, authenticated;

create policy interpreter_sessions_member_read
on public.interpreter_sessions
for select
to authenticated
using (
  exists (
    select 1
    from public.interpreter_session_members m
    where m.session_id = interpreter_sessions.id
      and m.user_id = (select auth.uid())
      and m.left_at is null
  )
);

create policy interpreter_session_members_self_read
on public.interpreter_session_members
for select
to authenticated
using (user_id = (select auth.uid()) and left_at is null);

create or replace function public.pantavion_create_interpreter_session(
  p_language_a text,
  p_language_b text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  actor uuid := auth.uid();
  lang_a text := lower(trim(coalesce(p_language_a, '')));
  lang_b text := lower(trim(coalesce(p_language_b, '')));
  pairing_code text;
  created_session public.interpreter_sessions%rowtype;
begin
  if actor is null then
    return jsonb_build_object('ok', false, 'error', 'authentication_required');
  end if;

  if char_length(lang_a) not between 2 and 35
     or char_length(lang_b) not between 2 and 35
     or lang_a = lang_b
     or lang_a !~ '^[a-z0-9-]+$'
     or lang_b !~ '^[a-z0-9-]+$' then
    return jsonb_build_object('ok', false, 'error', 'invalid_language_pair');
  end if;

  pairing_code := upper(encode(extensions.gen_random_bytes(8), 'hex'));

  insert into public.interpreter_sessions(
    created_by,
    language_a,
    language_b,
    pairing_code_hash
  ) values (
    actor,
    lang_a,
    lang_b,
    encode(extensions.digest(pairing_code, 'sha256'), 'hex')
  )
  returning * into created_session;

  insert into public.interpreter_session_members(session_id, user_id, role)
  values (created_session.id, actor, 'host');

  return jsonb_build_object(
    'ok', true,
    'sessionId', created_session.id,
    'pairingCode', pairing_code,
    'topic', 'interpreter:' || created_session.id::text,
    'languageA', created_session.language_a,
    'languageB', created_session.language_b,
    'pairingExpiresAt', created_session.pairing_expires_at,
    'expiresAt', created_session.expires_at,
    'role', 'host'
  );
end;
$$;

revoke all on function public.pantavion_create_interpreter_session(text, text) from public, anon;
grant execute on function public.pantavion_create_interpreter_session(text, text) to authenticated;

create or replace function public.pantavion_join_interpreter_session(
  p_pairing_code text
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  actor uuid := auth.uid();
  code text := upper(regexp_replace(trim(coalesce(p_pairing_code, '')), '[^A-F0-9]', '', 'g'));
  recent_attempts integer;
  attempt_id bigint;
  target public.interpreter_sessions%rowtype;
  existing_role text;
begin
  if actor is null then
    return jsonb_build_object('ok', false, 'error', 'authentication_required');
  end if;

  select count(*)::integer
  into recent_attempts
  from public.interpreter_pairing_attempts
  where user_id = actor
    and attempted_at > now() - interval '5 minutes';

  if recent_attempts >= 10 then
    return jsonb_build_object('ok', false, 'error', 'pairing_rate_limited');
  end if;

  insert into public.interpreter_pairing_attempts(user_id)
  values (actor)
  returning id into attempt_id;

  if char_length(code) <> 16 then
    return jsonb_build_object('ok', false, 'error', 'invalid_or_expired_pairing_code');
  end if;

  select s.*
  into target
  from public.interpreter_sessions s
  where s.pairing_code_hash = encode(extensions.digest(code, 'sha256'), 'hex')
    and s.pairing_expires_at > now()
    and s.expires_at > now()
    and s.status = 'pairing'
  for update
  limit 1;

  if target.id is null then
    return jsonb_build_object('ok', false, 'error', 'invalid_or_expired_pairing_code');
  end if;

  select m.role
  into existing_role
  from public.interpreter_session_members m
  where m.session_id = target.id
    and m.user_id = actor
    and m.left_at is null
  limit 1;

  if existing_role is not null then
    update public.interpreter_pairing_attempts
    set success = true, session_id = target.id
    where id = attempt_id;

    return jsonb_build_object(
      'ok', true,
      'sessionId', target.id,
      'topic', 'interpreter:' || target.id::text,
      'languageA', target.language_a,
      'languageB', target.language_b,
      'expiresAt', target.expires_at,
      'role', existing_role
    );
  end if;

  if exists (
    select 1
    from public.interpreter_session_members m
    where m.session_id = target.id
      and m.role = 'guest'
      and m.left_at is null
  ) then
    return jsonb_build_object('ok', false, 'error', 'pairing_session_full');
  end if;

  insert into public.interpreter_session_members(session_id, user_id, role)
  values (target.id, actor, 'guest');

  update public.interpreter_sessions
  set status = 'active',
      paired_at = coalesce(paired_at, now()),
      pairing_code_hash = null,
      updated_at = now()
  where id = target.id;

  update public.interpreter_pairing_attempts
  set success = true, session_id = target.id
  where id = attempt_id;

  return jsonb_build_object(
    'ok', true,
    'sessionId', target.id,
    'topic', 'interpreter:' || target.id::text,
    'languageA', target.language_a,
    'languageB', target.language_b,
    'expiresAt', target.expires_at,
    'role', 'guest'
  );
end;
$$;

revoke all on function public.pantavion_join_interpreter_session(text) from public, anon;
grant execute on function public.pantavion_join_interpreter_session(text) to authenticated;

create or replace function public.pantavion_close_interpreter_session(
  p_session_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  actor uuid := auth.uid();
  affected integer;
begin
  if actor is null then
    return jsonb_build_object('ok', false, 'error', 'authentication_required');
  end if;

  update public.interpreter_sessions
  set status = 'closed',
      closed_at = now(),
      pairing_code_hash = null,
      updated_at = now()
  where id = p_session_id
    and created_by = actor
    and status in ('pairing','active');

  get diagnostics affected = row_count;
  if affected = 0 then
    return jsonb_build_object('ok', false, 'error', 'session_not_found_or_not_owner');
  end if;

  update public.interpreter_session_members
  set left_at = coalesce(left_at, now())
  where session_id = p_session_id;

  return jsonb_build_object('ok', true, 'sessionId', p_session_id);
end;
$$;

revoke all on function public.pantavion_close_interpreter_session(uuid) from public, anon;
grant execute on function public.pantavion_close_interpreter_session(uuid) to authenticated;

create policy interpreter_private_realtime_read
on realtime.messages
for select
to authenticated
using (
  realtime.messages.extension in ('broadcast', 'presence')
  and exists (
    select 1
    from public.interpreter_session_members m
    join public.interpreter_sessions s on s.id = m.session_id
    where m.user_id = (select auth.uid())
      and m.left_at is null
      and s.status in ('pairing','active')
      and s.expires_at > now()
      and (select realtime.topic()) = ('interpreter:' || s.id::text)
  )
);

create policy interpreter_private_realtime_write
on realtime.messages
for insert
to authenticated
with check (
  realtime.messages.extension in ('broadcast', 'presence')
  and exists (
    select 1
    from public.interpreter_session_members m
    join public.interpreter_sessions s on s.id = m.session_id
    where m.user_id = (select auth.uid())
      and m.left_at is null
      and s.status in ('pairing','active')
      and s.expires_at > now()
      and (select realtime.topic()) = ('interpreter:' || s.id::text)
  )
);
